### ISSUE TITLE
Data download page: layout does not work on phone

### ISSUE THREAD

**Issue by mlennert** [OSGeo/grass-website#106]
On my phone the screenshot of the download button is squeezed next to the text which therefore does not have enough space. Not very nice to look at, not to read. I would suggest putting the screenshot after the text.

**Comment by mlennert** [comment]
Hi @lucadelu, thanks for the quick patch proposal. Any hints on how I could see how the result looks like on a phone without creating a web server my phone could connect to ?

**Comment by neteler** [comment]
In (desktop) Firefox, you can switch between desktop and phone layout (responsive design) with CTRL-SHIFT-M.

**Comment by lucadelu** [comment]
@mlennert just patch your local copy with the pull request, launch "hugo server" [firefox](https://developer.mozilla.org/en-US/docs/Tools) and [chromium](https://developer.mozilla.org/en-US/docs/Tools) have tools for web developers and you can switch between desktop, pad and mobile views

**Comment by mlennert** [comment]
Thanks for the hints on visualizing mobile version. Didn't know about that.

However, in the latest version in master, and therefore currently live version, there is nothing at all anymore on the data download in the startup GUI. Is that expected ?

**Comment by veroandreo** [comment]
> Thanks for the hints on visualizing mobile version. Didn't know about that.
> 
> However, in the latest version in master, and therefore currently live version, there is nothing at all anymore on the data download in the startup GUI. Is that expected ?

See #112, build works fine locally but not in the server for unknown reasons so far

**Comment by mlennert** [comment]
Thanks for the heads up. I have been in vidéoconférences almost continuously for the last 9 hours and haven't found the time or energy to follow GRASS website development...

**Comment by ninsbl** [comment]
This should be fixed by #107 
On my local build the page displays nice after Lucas change. 
Please reopen if issues remain after the server builds properly again.
