### ISSUE TITLE
hugo builds no longer work on server: Error building site

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#109]
The hugo builds no longer work on the server:

```
Total in 1716 ms
Error: Error building site: failed to render pages: render of "page" failed: "/home/neteler/grass-website/themes/grass/layouts/_default/single.html:37:29": execute of template failed: template: _default/single.html:37:29: executing "menu" at <.IsAncestor>: can't evaluate field IsAncestor in type source.File
```
Probably due to f372535464debafca0255c7b7d5e9c7efad50799 (?).

hugo version on server:

```
grass:~/grass-website$ hugo version
Hugo Static Site Generator v0.54.0/extended linux/amd64 BuildDate: 2019-06-04T19:16:36Z

grass:~/grass-website$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
```

**Comment by ninsbl** [comment]
Also, some content is not displayed any more, e.g.:
http://localhost:1313/download/data/
For display issues with a local build...

**Comment by veroandreo** [comment]
To get HTML tags displayed properly (including images and links), we need #42 merged... And hugo needs to be updated to the new 0.69 version in the server so that the site builds again

**Comment by nbozon** [comment]
Yes please update to Hugo v0.69 and it should build again...

**Comment by ninsbl** [comment]
Yes it builds indeed with v0.69. And I can confirm that content is diplayed again when #42 is merged, as @veroandreo pointed.
However, fonts seem to be different also with #42 applied...

**Comment by neteler** [comment]
> Yes please update to Hugo v0.69 and it should build again...

I am on Debian, no way to update easily on a production system. Debian Buster ships hugo v0.54.0... there is no more recent Debian release.

Now what to do?

**Comment by ninsbl** [comment]
Would the following be possible:

```
wget https://github.com/gohugoio/hugo/releases/download/v0.69.0/hugo_0.69.0_Linux-64bit.deb
dpkg -i hugo_0.69.0_Linux-64bit.deb
```

See: https://www.howtoforge.com/how-to-install-hugo-site-generator-on-ubuntu/

**Comment by neteler** [comment]
Cool, that worked (no dependency hell):

```
neteler@grass:~$ hugo version
Hugo Static Site Generator v0.69.0-4205844B linux/amd64 BuildDate: 2020-04-10T09:12:34Z
```

To keep an eye on, in case it gets replaced in a system update. I am not too much into Debian, so I don't know if and how version pinning (>= 0.69) could be done.

**Comment by neteler** [comment]
The site is built again, closing for now. Thanks, @ninsbl !

**Comment by neteler** [comment]
Update: I just discovered that the cronjob failed on the server after te hugo update due to path change...

In 10min it will run again, with corrected path to the hugo binary. I keep an eye on it (my benchmark is a typo on the main landing page which must disappear in 8 min from now :-) )

**Comment by neteler** [comment]
Success!

```
Cron <neteler@grass> cd /home/neteler/grass-website/ && git pull origin master && /usr/local/bin/hugo && rm -fr /var/www/html/*
        && \cp -rp /home/neteler/grass-website/public/* /var/www/html/ && cp -p /home/neteler/cronjobs/googleebda3c3d501e9945.html
        /var/www/html/

>From https://github.com/OSGeo/grass-website
 * branch            master     -> FETCH_HEAD
Already up to date.
Building sites …
                   | EN
-------------------+------
  Pages            | 161
  Paginator pages  |   0
  Non-page files   |  10
  Static files     | 971
  Processed images |   0
  Aliases          |   0
  Sitemaps         |   1
  Cleaned          |   0

Total in 15388 ms
```
