### ISSUE TITLE
Some HTML layouts and tags are not displayed after updating hugo in the server 

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#112]
See for example: 
- https://staging.grass.osgeo.org/learn/overview/ --> only titles displayed, no content nor images
- https://staging.grass.osgeo.org/download/addons/ --> no image
- https://staging.grass.osgeo.org/contribute/development/ --> no images
- https://staging.grass.osgeo.org/about/history/releases/ --> Only section titles displayed, no <li>, <a> or <img>
- https://staging.grass.osgeo.org/about/community/ --> no font awesome icons

When I build locally with hugo-extended v0.69dev installed from source, I get it mostly right except for some issues with img paths and appearance of home. See images below:

![image](https://user-images.githubusercontent.com/20075188/79166511-9ccec200-7de5-11ea-989d-2cc264202c3a.png)

![image](https://user-images.githubusercontent.com/20075188/79166255-0ac6b980-7de5-11ea-8117-c3a067b439eb.png)

![image](https://user-images.githubusercontent.com/20075188/79166300-203be380-7de5-11ea-9f11-d834bac918e5.png)

**Comment by lucadelu** [comment]
@veroandreo I think the problem is with path to images, I think the images were moved in sub directories, If the problem is this please check all the pages :-/

**Comment by veroandreo** [comment]
@lucadelu: In my local build, yes, but in the server the issue is different.

**Comment by nbozon** [comment]
I noticed most initial theme's images were removed from the root of static/images/ after subdirectories were created...  This is not a path problem, but simply missing images. They were deleted [11 days ago](https://github.com/OSGeo/grass-website/commit/e1070d4f68e08c74155d8532fe18245f31977cb2) it seems.. @veroandreo They are still rendered on the server because they are kept in /public from previous builds.

**Comment by lucadelu** [comment]
I still have them in a public folder, I could add back them...

**Comment by veroandreo** [comment]
Even with the fixes to the img file paths (#115), the site still doesn't display some HTML layouts and tags in the server. Meanwhile, it builds fine locally. There's some other problem, @nbozon. Please, have a look at the links I posted originally.

**Comment by nbozon** [comment]
Yes, i also noticed that every (html) bootstrap element is not rendered on "subpages" only.  Everything's rendered locally, but have no clue of what is happening on the server yet. I wonder if this may be related to the new use of [blackfriday](https://github.com/russross/blackfriday).

**Comment by veroandreo** [comment]
But I have the same fix locally and it looks fine... blackfriday was was the default html renderer in the previous hugo 0.54 version available in the server, so I do not know why it wouldn't work now there... The other option described [here](https://jdhao.github.io/2019/12/29/hugo_html_not_shown/) was to add the following in `config.toml` instead of the option proposed and merged in #42 :

```
[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
```
However, the effect should be the same... Maybe the installation in the server is missing some dependency??

**Comment by neteler** [comment]
> However, the effect should be the same... Maybe the installation in the server is missing some dependency??

I "simply" installed hugo v0.69.0-4205844B from deb package (following the suggestion here: https://github.com/OSGeo/grass-website/issues/109#issuecomment-613075361).
Happy to check on the server, but what for?

**Comment by neteler** [comment]
So, I have trashed the entire repo on the server and cloned again. As suspected, there was garbage left in the "public" directory (...I believe being "trapped" there due to the .gitignore change in d39978da86dcb5cdcec7603602f4847304924dbc).

Current state:

> See for example:
> 
>     https://staging.grass.osgeo.org/learn/overview/ --> only titles displayed, no content nor images

-> images and content are back.

>     https://staging.grass.osgeo.org/download/addons/ --> no image

-> image is back.

>     https://staging.grass.osgeo.org/contribute/development/ --> no images

--> dunno, which images should be there?

>     https://staging.grass.osgeo.org/about/history/releases/ --> Only section titles displayed, no

--> all back

>     https://staging.grass.osgeo.org/about/community/ --> no font awesome icons

--> font awesome icons seem to be back.

Summary: all fine again on the server (maybe) except for https://staging.grass.osgeo.org/contribute/development/ but I know know what might be missing here.

**Comment by veroandreo** [comment]
> So, I have trashed the entire repo on the server and cloned again. As suspected, there was garbage left in the "public" directory (...I believe being "trapped" there due to the .gitignore change in [d39978d](https://github.com/OSGeo/grass-website/commit/d39978da86dcb5cdcec7603602f4847304924dbc)).
> 
> Current state:
> 
> > See for example:
> > ```
> > https://staging.grass.osgeo.org/learn/overview/ --> only titles displayed, no content nor images
> > ```
> 
> -> images and content are back.
> 
> > ```
> > https://staging.grass.osgeo.org/download/addons/ --> no image
> > ```
> 
> -> image is back.
> 
> > ```
> > https://staging.grass.osgeo.org/contribute/development/ --> no images
> > ```
> 
> --> dunno, which images should be there?
> 
> > ```
> > https://staging.grass.osgeo.org/about/history/releases/ --> Only section titles displayed, no
> > ```
> 
> --> all back
> 
> > ```
> > https://staging.grass.osgeo.org/about/community/ --> no font awesome icons
> > ```
> 
> --> font awesome icons seem to be back.
> 
> Summary: all fine again on the server (maybe) except for https://staging.grass.osgeo.org/contribute/development/ but I know know what might be missing here.

Great news! Those are the images that were removed by #72 and that can either be restored o replaced with font awesome icons as suggested in #114. However, I don't know if fa icons can be aligned left and right as the original layout of the images.
