### ISSUE TITLE
PR #72 removed all images used in development page

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#114]
How can we restore them now? Needed images are:

- bugreport.svg
- document.svg
- translation.svg
- addons.svg
- core_devel.svg

@neteler is it possible to restore them and then fix the path in content/contribute/development?

**Comment by nbozon** [comment]
Or you may replace them using font-awesome icons as follow

Bug:

       <i class="fa fa-bug fa-3x"></i>

Document:

       <i class="fa fa-file-text fa-3x"></i>

Translattion:

       <i class="fa fa-language fa-3x"></i>

Addons (?) :
       
      <i class="fa fa-plug fa-3x"></i>  

Core dev:
       
      <i class="fa fa-gear fa-3x"></i>

**Comment by lucadelu** [comment]
> How can we restore them now? Needed images are:
> 
>     * bugreport.svg
> 
>     * document.svg
> 
>     * translation.svg
> 
>     * addons.svg
> 
>     * core_devel.svg
> 
> 
> @neteler is it possible to restore them and then fix the path in content/contribute/development?

I have them, but I also like the @nbozon idea.. what do you think?

**Comment by neteler** [comment]
I have them locally, too (sorry for the removal by mistake!). I also like the idea of using font-awesome icons, shall we give it a try?

**Comment by veroandreo** [comment]
Yes, let's use @nbozon's suggestion, I like it :)

**Comment by neteler** [comment]
The solution proposed above by @nbozon has been implemented and now looks like this:

https://staging.grass.osgeo.org/contribute/

Question: shall we upload (as per #119, but with path removal modifications) the SVG files anyway?

**Comment by neteler** [comment]
Can we close this or are the SVGs still desired? (AFAIK they are stored in the git history anyway)
