### ISSUE TITLE
Empty "community" page under Contribute

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#116]
Can we remove that one since we already have one with content under `About`?

**Comment by lucadelu** [comment]
I agree

**Comment by neteler** [comment]
It's gone, closing

**Comment by veroandreo** [comment]
It's still there... empty

**Comment by neteler** [comment]
I really don't see it, which URL?

But this one is also a "ghost": https://staging.grass.osgeo.org/contribute/ (<- empty)

**Comment by veroandreo** [comment]
> I really don't see it, which URL?

in the files in the repo. I addressed that also in #118 

> But this one is also a "ghost": https://staging.grass.osgeo.org/contribute/ (<- empty)

This is the one being changed with #118 and #119

**Comment by veroandreo** [comment]
This was done in #118, so closing
