### ISSUE TITLE
Add "Edit on GitHub" footer to landing pages too

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#117]
Is it possible to have the "Edit on GitHub" footer also in landing pages like `Learn`, `Download` and `Contribute`? Or is there a reason why it is only in the subpages?

**Comment by nbozon** [comment]
This was added only on "subpages" , because i don't think we want people to edit these index pages (as their content is mostly html and are more complex than just markdown). But yes, the link can be added there too if it is needed -

**Comment by veroandreo** [comment]
Right, I understand. In any case, the workflow should always be PR. 

I don't have a strong opinion about it. What do others think?

**Comment by lucadelu** [comment]
I also would like to have it

**Comment by mlennert** [comment]
I also vote for the link on landing pages.

**Comment by lucadelu** [comment]
I fixed it in #158, now it is visible everywhere except for home page since it is only layout and it is not really simple to modify, but if you like to have the link also there it is possible to add
