### ISSUE TITLE
What to add in the side panel of 'Get involved' landing page?

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#120]
What shall we add in the side green panel of the `Get involved` landing page?? Links to what? Pictures? 

@nbozon, any ideas??

**Comment by lucadelu** [comment]
I would like to remove it, most of the pages have just one column, I would like to remove the side panel also from the others pages having it (About -> community, About -> Credits)

**Comment by veroandreo** [comment]
I don't want to remove them, I like them indeed. Otherwise pages are too boring. But, I'd like to hear some ideas of what to put there or which other layout to use.

**Comment by veroandreo** [comment]
@nbozon how do I edit the `themes/grass/layouts/contribute/contribute.html` file in order to see sections' links in the side-panel?

**Comment by lucadelu** [comment]
I was checking again the website and I found again really bed two see two columns in `Contribute` page. Please look in order `Download`, `Learn`, `Contribute`, `About` pages and let me know if you don't see something strange in `Contribute`, all the others pages are one column only (`Learn` is not completely one column but is one row)

**Comment by mlennert** [comment]
I'm more with @lucadelu on this one. I don't really like those green side panels either, especially since they significantly reduce the width of the main body, but also because I do think having a homogeneous look and feel to all the pages is actually better (even if boring...).

**Comment by ninsbl** [comment]
On this one I also agree with @lucadelu. Esp. if we have challenges with filling them with useful information. Note also that they behave a bit strange on mobile (stay on top of the page).
At least for the time being I would just remove them to get the cool new website online. They can always be added back once we have a good plan for how to use them...

**Comment by veroandreo** [comment]
Fine for me, please go ahead... Still, it would be nice to understand how to edit them if we want to add them back in the future
