### ISSUE TITLE
Move News outside About?

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#121]
I believe we should move `News` outside `About`. IMO it should be a separate menu item (even if it does not have submenus), maybe the first one in the bar. What do you think?

**Comment by hellik** [comment]
+1

**Comment by lucadelu** [comment]
I prefer the actual solution, because News are "about" GRASS and they are already in the home page

**Comment by neteler** [comment]
> I prefer the actual solution, because News are "about" GRASS and they are already in the home page

True but then you only find them when on the home page itself. In my view the "News" in "About" are too much hidden and making the submenu list too long.

**Comment by veroandreo** [comment]
> I prefer the actual solution, because News are "about" GRASS and they are already in the home page

Did you try #122? I think it looks nicer and in that way we don't clutter About with so many items. Moreover, I also followed your own opinion here: https://github.com/OSGeo/grass-website/issues/32#issuecomment-606293836

**Comment by hellik** [comment]
> > I prefer the actual solution, because News are "about" GRASS and they are already in the home page
> 
> True but then you only find them when on the home page itself. In my view the "News" in "About" are too much hidden and making the submenu list too long.

I concur

**Comment by neteler** [comment]
For the ease of judging, here a screenhot how it would look like after applying this PR:

![image](https://user-images.githubusercontent.com/1295172/79729397-b5604000-82ef-11ea-94f6-0c222bc027b5.png)

(again, the news would be then always reachable, regardsless which page one visits)

Mobile view:
![image](https://user-images.githubusercontent.com/1295172/79729600-f9534500-82ef-11ea-9abd-5b4db8999932.png)

**Comment by ninsbl** [comment]
I would also prefer to have News as menu item (without submenues).
So I am +1 for merging #122 With the change for News

**Comment by neteler** [comment]
@mlennert what do you think?

**Comment by mlennert** [comment]
+1 for the separate News item, if we can ensure that we have enough news to warrant it ;-)

**Comment by veroandreo** [comment]
done in #122, closing
