### ISSUE TITLE
Mac downloads: Delete a reference to frameworks

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#126]
_Michael Barton wrote:_

Yes. I was looking at the current site not the new one in development.

On the old site, all listed versions should perhaps say:

"These are all-inclusive GRASS binary apps. They include all needed dependencies, as well as required Python and wxPython versions. GRASS 7.8.2 and higher versions are compiled with Python 3; earlier versions are compiled with Python 2.7. "

Delete a reference to frameworks

The links for GRASS 7.6 and 7.8 are http://grassmac.wikidot.com
The link for GRASS 7.9 is http://grassmac.wikidot.com/downloads

Both are correct but we should probably be consistent.
http://grassmac.wikidot.com/downloads goes directly to my download page
http://grassmac.wikidot.com goes to the main site page with some information about GRASS in general and an overview of the binaries.

-----

For the new site, the Kingchaos site refers back to my site. So it should not be listed for binaries. The frameworks on that site are only useful for very old versions of my binaries, but may be useful for homebrew (I don't know).

With the recent bug fixes, I do now have binaries for GRASS 7.8.2 and 7.9. I use 7.8.2 RB instead of stable because it has important bug fixes needed for compiling and for the digitizer.

Vaclav may have an Anaconda recipe working (not sure where that is, but he was close a couple weeks back) that should probably also be listed if working.

Thanks
Michael

____________________
C. Michael Barton
Director, Center for Social Dynamics & Complexity
Professor of Anthropology, School of Human Evolution & Social Change
Head, Graduate Faculty in Complex Adaptive Systems Science
Arizona State University

_Originally posted by @cmbarton in https://github.com/OSGeo/grass-website/issues/124#issuecomment-619613005_

**Comment by neteler** [comment]
## Old site

> On the old site, all listed versions should perhaps say:
> 
> "These are all-inclusive GRASS binary apps. They include all needed dependencies, as well as required Python and wxPython versions. GRASS 7.8.2 and higher versions are compiled with Python 3; earlier versions are compiled with Python 2.7. "

I have added the sentence.
 
> Delete a reference to frameworks

Framework reference deleted.
 
> The links for GRASS 7.6 and 7.8 are http://grassmac.wikidot.com
> The link for GRASS 7.9 is http://grassmac.wikidot.com/downloads

... this was already the case, wasn't it?

Old (and still actual) site - please verify:

https://grass.osgeo.org/download/software/mac-osx/


## New site

> For the new site, the Kingchaos site refers back to my site. So it should not be listed for binaries. The frameworks on that site are only useful for very old versions of my binaries, but may be useful for homebrew (I don't know).

Please edit the page directly and submit a pull request (can even be done from via browser) as I am very tight on time:

* https://staging.grass.osgeo.org/download/mac/
* Edit: https://github.com/OSGeo/grass-website/blob/master/content/download/mac.en.md

Thanks

**Comment by cmbarton** [comment]
On Apr 27, 2020, at 2:22 PM, Markus Neteler <notifications@github.com<mailto:notifications@github.com>> wrote:


This link

The links for GRASS 7.6 and 7.8 are http://grassmac.wikidot.com

is different from this link

The link for GRASS 7.9 is http://grassmac.wikidot.com/downloads

Either one is OK but they should probably be the same.

The 2nd one goes directly to the download page.


... this was already the case, wasn't it?

Old (and still actual) site - please verify:

https://grass.osgeo.org/download/software/mac-osx/

Otherwise the new text looks good. Thanks.

Michael


____________________
C. Michael Barton
Director, Center for Social Dynamics & Complexity
Professor of Anthropology, School of Human Evolution & Social Change
Head, Graduate Faculty in Complex Adaptive Systems Science
Arizona State University

voice:  480-965-6262 (SHESC), 480-965-8130/727-9746 (CSDC)
fax: 480-965-7671 (SHESC),  480-727-0709 (CSDC)
www: http://www.public.asu.edu/~cmbarton, https://complexity.asu.edu/csdc

**Comment by neteler** [comment]
I have streamlined the download links.

**Comment by cmbarton** [comment]
Looks good. Thanks. 

Michael

**Comment by neteler** [comment]
TODO:

> ## New site
> 
> > For the new site, the Kingchaos site refers back to my site. So it should not be listed for binaries. The frameworks on that site are only useful for very old versions of my binaries, but may be useful for homebrew (I don't know).
> 
> Please edit the page directly and submit a pull request (can even be done from via browser) as I am very tight on time:
> 
>     * https://staging.grass.osgeo.org/download/mac/
>     * Edit: https://github.com/OSGeo/grass-website/blob/master/content/download/mac.en.md
>

**Comment by cmbarton** [comment]
OK. Backed up today but will do this. Thanks for the link.

Michael

**Comment by cmbarton** [comment]
I did a pull request with changes. Preview is really bad so I hope that it actually looks OK. 

Michael

**Comment by neteler** [comment]
Thanks for the fixes.

All updated also here: https://staging.grass.osgeo.org/download/mac/
