### ISSUE TITLE
License subpage: side menu and bottom of the page

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#127]
The side menu in `About/License` shows links to all files in the folder (as the issue solved for `About` landing page in d4c0d5cabf7ef5508c7a190e5df618e98a14f94f). Can we fix it here too or maybe change the layout, @nbozon ?

Moreover, the bottom of the page shows "updated + date in the header of the file". Any other page displays that, so IMO it should be removed. How can we remove that?

**Comment by nbozon** [comment]
@veroandreo , yes we should probably use a different layout here. The 'Updated +date' comes from the 'general' template i believe. I will look at and fix it ASAP -

**Comment by lucadelu** [comment]
Should be fixed
