### ISSUE TITLE
How to deploy on the server: static content vs hugo driven content

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#129]
I am unsure how to deploy the new, beautiful pages on the server (grasslxd container, currently https://staging.grass.osgeo.org/).

## The problem

* we have hugo driven content (managed here in GH)
* we have static content (esp. the `grassXX/` subdirectories which are stored not in GH)

At time the cronjob on the server simply wipes out the target www/ directory and copies over the static site built with hugo. But this will no longer be possible as soon as the `grassXX/` subdirectories are migrated to the grasslxd container.

Ideas?

**Comment by mlennert** [comment]
Would it be possible to keep grassXX outside the www/ directory and after deployment of the hugo content link them in by symbolic link ? Should be a simple oneliner in a deployment script.

**Comment by neteler** [comment]
> Would it be possible to keep grassXX outside the www/ directory and after deployment of the hugo content link them in by symbolic link ? Should be a simple oneliner in a deployment script.

Yes, good idea. I am currently copying over the data (15GB) into a separate directory. Will report back once done...

**Comment by landam** [comment]
> At time the cronjob on the server simply wipes out the target www/ directory and copies over the static site built with hugo. But this will no longer be possible as soon as the `grassXX/` subdirectories are migrated to the grasslxd container.

@neteler What you exactly mean by "migrated"? I have no experience with lxd containers, but isn't possible to mount volume (with `grassXX` directories) as it works for dockers?

**Comment by neteler** [comment]
> > At time the cronjob on the server simply wipes out the target www/ directory and copies over the static site built with hugo. But this will no longer be possible as soon as the `grassXX/` subdirectories are migrated to the grasslxd container.
> 
> @neteler What you exactly mean by "migrated"? I have no experience with lxd containers, but isn't possible to mount volume (with `grassXX` directories) as it works for dockers?

Well, here it is all in the container. I simply moved all the old (CMS) server content over and cleaned it up. Done.

**Comment by neteler** [comment]
> Would it be possible to keep grassXX outside the www/ directory and after deployment of the hugo content link them in by symbolic link ? Should be a simple oneliner in a deployment script.

Data (software versions and sample data) copied over, link creation cronjob in place.

![image](https://user-images.githubusercontent.com/1295172/81455453-8e2ebd00-918f-11ea-90e1-6e8cb121cd22.png)


Seems to work (and beloved timestamps preserved since 1996)!

E.g.
https://staging.grass.osgeo.org/grass78/source/

Let's monitor this a bit, then this ticket is probably done.

**Comment by neteler** [comment]
One showstopper found...: https://github.com/OSGeo/grass-website/issues/22#issuecomment-626062819

**Comment by neteler** [comment]
Note to self: the weekly cronjob seems to be failing:
https://staging.grass.osgeo.org/grass78/source/snapshot/

**Comment by neteler** [comment]
Since the snapshots cronjobs are working now, I think we can close this issue.
