### ISSUE TITLE
Can Google Font API usage be avoided?

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#13]
At time the style contains

```
  <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,600,700,700i,800&display=swap" rel="stylesheet">
  <link href="https://mapskincdn.appspot.com/2.0/mapskin.min.css" rel="stylesheet">
```

Like this, our visitors become known to Google through the related font API accesses including their behaviour of visiting our web site.

No high priority but more important than a "nice to have" (for me).

**Comment by nbozon** [comment]
Yes, they can be avoided, good point @neteler

**Comment by nbozon** [comment]
Done for Lato and Open Sans:

- Lato was completly removed as it wan't used anywhere

- Open Sans google font was replaced by a local webfont now hosted in static//plugins/open-sans/

Mapskin webfont was also added as local ressource, but doesn't work as expected for now... will fixed this asap

**Comment by nbozon** [comment]
Looks like this for now

```
     <link rel="stylesheet" href="https://staging.grass.osgeo.org/plugins/open-sans/open-sans.css" >
     <link href="https://mapskincdn.appspot.com/1.0/mapskin.min.css" rel="stylesheet">
     <!--  <link rel="stylesheet" href="https://staging.grass.osgeo.org/plugins/mapskin/mapskin.min.css" > -->
```

**Comment by nbozon** [comment]
No more request to Google servers @neteler :)
Both Open Sans and mapskin are now stored locally and fully supported in production

    <link rel="stylesheet" href="{{ .Site.BaseURL }}plugins/open-sans/open-sans.css" >
    <link rel="stylesheet" href="{{ .Site.BaseURL }}plugins/mapskin/css/mapskin.min.css">

**Comment by neteler** [comment]
Thanks, @nbozon !

**Comment by veroandreo** [comment]
can we close this one and mark as done?

**Comment by nbozon** [comment]
yes this is done, please close @veroandreo
