### ISSUE TITLE
Allow bigger sizes for font awesome icons

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#135]
Following the logic of the css in `themes/grass/static/plugins/fontawesome/css/font-awesome.css`, I tried adding larger sizes
```
.fa-7x {
  font-size: 7em;
}
.fa-9x {
  font-size: 9em;
}
```
but it didn't change anything. Indeed, with size > 5x the icon gets small again. Is there something else that should be changed to make it work?

**Comment by lucadelu** [comment]
I don't know why but .fa-7x and .fa-9x are missing in font-awesome.css, added in our style with #151
