### ISSUE TITLE
add content to Development page

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#137]
Since most of the content in the former `development` page was moved to the landing page of `Get involved`, now we need to add some more info only about development into the sub-page. Ideas?

**Comment by lucadelu** [comment]
I already suggested to remove `development` page in [previous discussion](https://github.com/OSGeo/grass-website/issues/77#issuecomment-612905277), I'm still of the same opinion

**Comment by neteler** [comment]
Suggestion:

In the main menu:
- Contribute > Development (at time https://staging.grass.osgeo.org/contribute/development/) 

... change to
- Contribute > Get involved (https://staging.grass.osgeo.org/contribute/) 

Done. Opinions?

**Comment by veroandreo** [comment]
I don't think we should remove it. I think a minimum explanation of how grass development works, link to development manuals and style guides, requirements to fulfill, must be there. Moreover, once we agree on a roadmap, I suggest to include it there. So it's easily discoverable and not hidden within trac. See for example these 3 QGIS pages: 
- https://qgis.org/en/site/getinvolved/development/contributor_requirements.html
- https://qgis.org/en/site/getinvolved/development/development.html
- https://qgis.org/en/site/getinvolved/development/roadmap.html

In this line of thought, some of the content in these pages might be recycled, for example, to get something similar to what QGIS have:
- https://grasswiki.osgeo.org/wiki/Development
- https://trac.osgeo.org/grass/wiki/HowToContribute
- https://trac.osgeo.org/grass/wiki/HowToGit

**Comment by veroandreo** [comment]
Any volunteers more familiar with Development stuff as to add some content to this page??

**Comment by wenzeslaus** [comment]
I don't know how this fits into this discussion, but there is a file https://github.com/OSGeo/grass/blob/master/CONTRIBUTING.md which should the somewhat the primary place at least for contributing directly to the main repo.

**Comment by mlennert** [comment]
This also might be a good entry point for new developers: [https://grasswiki.osgeo.org/wiki/GRASS_GIS_APIs](https://grasswiki.osgeo.org/wiki/GRASS_GIS_APIs).

**Comment by ninsbl** [comment]
Personally, I would probably move the content from the landing page (BTW. quicklinks at the top would be helpful here given the length and different topics) to "Development" and the content from Development (with minor addition of info on the different ways people can contribute and links to the respective sub-pages) to the landing page. Adding links to external sites that are listed above can be a good way not overload the new website. However, it seems that some consolidation and update of the different pages would be necessary in the long run.
I can try to come up with a proposal / PR tonight if you like...

**Comment by veroandreo** [comment]
> Personally, I would probably move the content from the landing page (BTW. quicklinks at the top would be helpful here given the length and different topics) to "Development" and the content from Development (with minor addition of info on the different ways people can contribute and links to the respective sub-pages) to the landing page. 

I did exactly the opposite (move most of development page to the landing page of contribute in #118) because that's what we had agreed in the call and was documented in #77. 
I really like how that landing page looks like... and the content fits... it's about the many ways you can contribute to the project or get involved with the community. 
Instead, the development page within the contribute section should be more technical for those contributing only to the source code

Adding links to external sites that are listed above can be a good way not overload the new website. However, it seems that some consolidation and update of the different pages would be necessary in the long run.
> I can try to come up with a proposal / PR tonight if you like...

**Comment by mlennert** [comment]
I also like the landing page the way it is now. Development should really focus on programming, so as a baseline it should provide a series of (commented) links to relevant resources. I see at least:

- https://grass.osgeo.org/programming7/

- https://grasswiki.osgeo.org/wiki/GRASS_GIS_APIs

- One of https://github.com/OSGeo/grass/blob/master/CONTRIBUTING.md or https://trac.osgeo.org/grass/wiki/HowToGit, but I would favor the former as it probably is where such info will be in the future.

- Possibly also https://grasswiki.osgeo.org/wiki/Development, but this probably needs some cleaning up and updating.

Plus maybe a link to the grass-dev list ?

At this stage, I think we should create the minimal page needed for the site to go online. Future enhancements will always be possible (but will also depend on the future uses of the grasswiki, trac wiki and github for such documentation).

**Comment by lucadelu** [comment]
I start to work on it, do we need more text?

**Comment by mlennert** [comment]
I'm removing the blocker flag as I think the page is ok for release as is right now. Obviously it could probably be improved by giving more guidance to the different links in the quick links section, i.e. some explanation of what each page contains.

**Comment by mlennert** [comment]
@veroandreo what do you think ?

**Comment by veroandreo** [comment]
I agree with removing the blocker tag (that you did already :)) but let's keep this issue open, as it contains a good list of sources where to obtain info from for further improvement of the Development page

**Comment by veroandreo** [comment]
closing as completed, also see upcoming changes at #414
