### ISSUE TITLE
Remove links to grass user groups 

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#14]
The GRASS user groups section looks very nice, but all links are very old (do not show any activity for the past 4-6 years), do not exist or just point to local OSGeo chapters. Hence, I'd just comment out that section. Opinions?

**Comment by neteler** [comment]
Since PR #14 was merged, anything missing here?

http://staging.grass.osgeo.org/about/community/

**Comment by veroandreo** [comment]
Not in my opinion, closing the issue
