### ISSUE TITLE
Add link to GRASS GIS google scholar citations

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#149]
I think it would be nice to add a link to the [Google Scholar GRASS profile](https://scholar.google.com/citations?user=gJ0ZB0cAAAAJ) somewhere in the website to show the various application fields of GRASS. What do you think?

**Comment by lucadelu** [comment]
Yes, maybe we could add it in community page under social media (I know it is not a social media, but otherwise I don't know where to put it) and as link in the Learn menu (like the wiki)

**Comment by neteler** [comment]
In addition, we may also add a snippet in the [contribute](https://staging.grass.osgeo.org/contribute/) page like "Please cite GRASS GIS to raise awareness .... visibility ... etc." as it is also a way to contribute.
