### ISSUE TITLE
Problem with tablets icon visualization

### ISSUE THREAD

**Issue by lucadelu** [OSGeo/grass-website#150]
There is a problem with icon visualization in tablets (working on mobiles and desktop), see #113

**Comment by nbozon** [comment]
@lucadelu can you be more specific on this issue please ? what problem with which icons ?  screenshot available, or guidance to reproduce ? thx

**Comment by lucadelu** [comment]
@nbozon you are right, sorry. The icon for addons and source code in tab mode is smaller then others, I'm not able to set the right dimension, probably I set wrong value for number of pixels (in desktop and mobile mode is working well)

![small_icon](https://user-images.githubusercontent.com/178741/82815904-6ed7a580-9e9a-11ea-92ae-70e463e5b27d.png)

**Comment by nbozon** [comment]
Fixed in master (i just increased the % size of .grasslogo in the tablets media query). 
Please review and close @lucadelu 

<img width="363" alt="Capture d’écran 2020-06-07 à 18 09 02" src="https://user-images.githubusercontent.com/7135374/83973948-0c46c680-a8ea-11ea-81fd-e41825f5b349.png">
