### ISSUE TITLE
Mobile: low contrast in text on main page

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#159]
The full name of the software is hard to read on mobile - see in the middle of the screenshot (interestingly, the contrast is higher on my laptop!):

![Screenshot_20200524_103714](https://user-images.githubusercontent.com/1295172/82751241-32327e00-9db6-11ea-8389-3a2a941da71a.jpg)

Maybe trivial to fix but it should be improved.

**Comment by lucadelu** [comment]
With #160 should be better

![section_title_dark](https://user-images.githubusercontent.com/178741/82817089-a34c6100-9e9c-11ea-93d4-3684e9d07c38.png)
