### ISSUE TITLE
Please add RSS support for planet.osgeo.org etc

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#167]
In order to feed http://planet.osgeo.org/ and other news aggregate sites as before we would need RSS support on the new server as well.

Apparently Hugo ships with its own RSS 2.0 template which might be used here:
https://gohugo.io/templates/rss/

thanks

**Comment by nbozon** [comment]
Yes, Hugo ships with a RSS template, which is generated from all published standard pages by default when building, see: https://staging.grass.osgeo.org/index.xml (or see [index.xml.txt](https://github.com/OSGeo/grass-website/files/4742680/index.xml.txt) for reference)

**Comment by nbozon** [comment]
Done @neteler 

The default Hugo default RSS template first needs to be copied, see:
https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/_default/rss.xml
And modified as follows (This generate RSS for thefirst 15 items of the News section only)

     {{ range first 15 (where .Site.Pages ".Section" "news") }}

The RSS link is also generated in the header partial, when applicable, using:

       {{ "" | safeHTML }}
       {{ with .OutputFormats.Get "rss" -}}
       {{ printf `<link rel="%s" type="%s" href="%s" title="%s" />` .Rel .MediaType.Type .Permalink 
       $.Site.Title | safeHTML }}
       {{ end -}}

An RSS link with icon is finally added in the website footer, adding an additional socialIcon param in config.toml

    [[Languages.en.socialIcon]]
      icon = "fa fa-rss"
      link = "https://staging.grass.osgeo.org/index.xml" 

The newly generated RSS feed is available here:
https://staging.grass.osgeo.org/index.xml

**Comment by neteler** [comment]
Cool, @nbozon - thanks a lot!
