### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#172]
And here's the related error message in the dev console: 
```
Cross-Origin Request Blocked: 
The Same Origin Policy disallows reading the remote resource at https://staging.grass.osgeo.org/plugins/open-sans/fonts/opensans-regular-webfont.woff. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://staging.grass.osgeo.org’).
```

_Originally posted by @mlennert in https://github.com/OSGeo/grass-website/issues/22#issuecomment-644629058_

**Comment by neteler** [comment]
This affects all mirrors rsyncing us.

**Comment by mlennert** [comment]
Should have posted it here and not in #22:

Reading some more on the subject, I'm pretty convinced that the config has to be changed on our side. I've posted the question at https://trac.osgeo.org/osgeo/ticket/2427#comment:5.

https://github.com/OSGeo/grass-website/issues/22#issuecomment-648825329_

**Comment by mlennert** [comment]
Another option would be to not download fontawesome into our site and serve it from there, but rather to use a Font Awesome CDN : https://fontawesome.com/v4.7.0/get-started/.

@nbozon any reason why not to use the CDN ?

**Comment by neteler** [comment]
> @nbozon any reason why not to use the CDN ?

One reason might be "privacy": to not expose the IPs etc of our visitors to a 3rd party. Of course that can be discussed how important we rate that...

**Comment by mlennert** [comment]
Seems to be solved by config change in the webserver.

If someone else can confirm, we can close this. And for me this would mean that we should be able to release the website ASAP.

**Comment by ninsbl** [comment]
Looks good.

**Comment by neteler** [comment]
Cool, Problem solved!

**Comment by neteler** [comment]
Might it be needed to also add .js to


 `<FilesMatch ".(eot|otf|ttf|woff|woff2)">`

(See above)
M
