### ISSUE TITLE
Fontawesome icons issue

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#175]
Is it possible that the icons are now gone, @lucadelu ?
The main page, this one:
https://staging.grass.osgeo.org/download/addons/

now show

![image](https://user-images.githubusercontent.com/1295172/85232653-d8e35c00-b400-11ea-818e-1e411e16e762.png)

_Originally posted by @neteler in https://github.com/OSGeo/grass-website/pull/166#issuecomment-647166455_

**Comment by nbozon** [comment]
@neteler  @lucadelu  All icons are now back, after i commented out the link to FontAwesome 5 (Both v4.7 and v5 were called from head.html btw, but they can't work together)

I would prefer that we stick to FontAwesome 4.7 if possible. If you want to upgrade to v5 (and there will be a v6 soon fyi), we then need to change all the icons markup (and possibly find alternatives for icons that would be available in v4.7 and not in v5)

Exemple using v4.7, as we are doing now:

    <i class=" fa fa-github"></i>

Should become the following using v5:

    <i class=" fab fa-github"></i>

**Comment by neteler** [comment]
Thanks, 1d9c3782026fb378983bca73a17c9b72c791bcdb brought the icons back.

**Comment by lucadelu** [comment]
Some icons are missing in https://staging.grass.osgeo.org/contribute/development/ we need to find icons from v4.7 for `API's wiki page`, `How to use git`, `GRASS Developers Mailing list` in the right sidepanel

**Comment by veroandreo** [comment]
I don't remember what was there before from version 5, but I'm having a look at icons here: https://fontawesome.com/v4.7.0/icons/

Suggestions:
- How to use git: code-fork
- API's wiki page: wikipedia-w or gears or info
- GRASS dev mailing list: envelope or pencil-square-o
