### ISSUE TITLE
Improve gallery of screenshots

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#179]
Even after removing many screenshots (#168) to avoid having them displayed automatically in the gallery, the visitor must still scroll quite a bit to have an overview. Moreover, it takes a while to load all images. In the merged PR #133 there is a suggestion on how to enhance it and other ideas: 

- Display only a couple of rows of screenshots per topic and add a `See more` link below or above them (see https://github.com/OSGeo/grass-website/pull/133#issuecomment-623194018 for a suggestion on how to implement it)
- Create some composite screenshots
- Add GRASS GIS versions within topics

**Comment by mlennert** [comment]
To be fair, you can click on a category on the left to jump to the images in that category.
But I agree that this should be enhanced.

**Comment by nbozon** [comment]
This improvement was added to master, according to the first proposal by @veroandreo and discussion in #133.
https://grass.osgeo.org/learn/gallery/

Each gallery now displays maximum 6 images per default at page init:

        .gallery div:nth-child(n+7) {display: none;}

A 'view more' / 'view less' toggler link is added bellow each gallery:

        <div id="gallery-wrapper">
          {{< gallery dir="/images/gallery/gui/" />}}
         <a href="#" class="gallery-toggler pull-right">View more</a>
        </div>

Some Jquery is finally added to script.js for toggling remaining images, as follows:

        $(".gallery-toggler").click(function(e){
         $(this).parent().find('.gallery div:nth-child(n+7)').toggle();
         $(this).html($(this).html() == 'View more' ? 'View less' : 'View more');
         e.preventDefault();
        });

@veroandreo @mlennert @lucadelu  , i believe this fixes the requested improvement 
Could you please close this issue ? - Thanks in advance

**Comment by veroandreo** [comment]
Thanks, @nbozon 

I found however that if I click in `View more` in Raster support section, all other sections get expanded while keeping the `View more` below them, and I'm redirected to all the screenshots from the GUI section. When I click on `View more` in the Remote Sensing section, the same happens and I'm shown the vector screenshots.

It all works as expected though when clicking over `View more` in GUI and Vector support sections (i.e., the other sections do not get expanded).

**Comment by nbozon** [comment]
Oops, forgotten divs...
This should be fixed now at https://grass.osgeo.org/learn/gallery/
(and btw, the 3d, Lidar and Cartography sections should get more than 6 screenshots in their respective directory :)

**Comment by lucadelu** [comment]
@nbozon thanks a lot it is working properly now!
