### ISSUE TITLE
Add list of mirror sites

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#181]
At time we do not have any list of mirror sites nor the rsync mirroring command line documented in order to become a new mirror site.
(in the old CMSMS it was here: https://grass.osgeo.org/mirrors/)

Any suggestions where to add this in the new site?

Note: the contact addresses for the mirror sites are hidden in this page <strike>https://grass.osgeo.org/mirrors/</strike> - now https://old.grass.osgeo.org/mirrors/

_Originally posted by @neteler in https://github.com/OSGeo/grass-website/issues/22#issuecomment-625293231_

**Comment by neteler** [comment]
BTW: notification sent to those operating GRASS GIS mirror sites:
https://lists.osgeo.org/pipermail/grass-web/2020-July/005062.html

**Comment by mlennert** [comment]
On 1/07/20 17:26, Markus Neteler wrote:
> At time we do not have any list of mirror sites nor the rsync mirroring 
> command line documented in order to become a new mirror site.
> (in the old CMSMS it was here: https://grass.osgeo.org/mirrors/)
> 
> Any suggestions where to add this in the new site?

Maybe a new "Mirror web site" page in the 'Contribute' section ?

As to the list of mirrors, this should probably be easily accessible 
from the general landing page, no ? Maybe a link in the footer to a page 
with the list of existing mirrors ?

BTW: is it on purpose that https://grass.osgeo.org alreay points to the 
new website before the official release ?

**Comment by neteler** [comment]
> Maybe a new "Mirror web site" page in the 'Contribute' section ?

Do you mean here as a menu entry?
![image](https://user-images.githubusercontent.com/1295172/88669500-419ab400-d0e4-11ea-99ce-31f522d08915.png)

I think it was Nick's utmost wish to keep the number of entries low...

> As to the list of mirrors, this should probably be easily accessible from the general landing page, no ? Maybe a link in the footer to a page with the list of existing mirrors ?

Yes, exactly my thought.

> BTW: is it on purpose that https://grass.osgeo.org alreay points to the new website before the official release ?

Yes, because it is a terrible amount of work (compare #180 ) and we already found numerous issues (some fixed).

**Comment by mlennert** [comment]
On 28/07/20 15:10, Markus Neteler wrote:
>     Maybe a new "Mirror web site" page in the 'Contribute' section ?
> 
> Do you mean here as a menu entry?
> image 
> <https://user-images.githubusercontent.com/1295172/88669500-419ab400-d0e4-11ea-99ce-31f522d08915.png>

Yes

> I think it was Nick's utmost wish to keep the number of entries low...

I've understood the same, yes, but I just don't see a logical place to 
put information on mirroring the website so that people will find it. 
Maybe on the Contribute landing page:

https://grass.osgeo.org/contribute/

?

But I'm not sure how many people will land on these landing pages as I 
would think people will often go straight to the individual pages via 
the menu (but I'm no UX expert).

> 
>     As to the list of mirrors, this should probably be easily accessible
>     from the general landing page, no ? Maybe a link in the footer to a
>     page with the list of existing mirrors ?
> 
> Yes, exactly my thought.

Not sure if this should be on every page footer, or only the main page ?

> 
>     BTW: is it on purpose that https://grass.osgeo.org alreay points to
>     the new website before the official release ?
> 
> Yes, because it is a terrible amount of work (compare #180 
> <https://github.com/OSGeo/grass-website/issues/180> ) and we already 
> found numerous issues (some fixed).

Ok, I understand. Just wanted to make sure this was on purpose. I hadn't 
seen the relavant message on grass-web: 
https://lists.osgeo.org/pipermail/grass-web/2020-July/005061.html.

**Comment by neteler** [comment]
All done here: https://grass.osgeo.org/about/mirrors/
