### ISSUE TITLE
Mobile Friendliness Test Tool complains about "Viewport not configured correctly"

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#182]
Testing the Mobile Friendliness with https://www.bing.com/webmaster/tools/mobile-friendliness it reported today:

URL: staging.grass.osgeo.org

```
This page is mobile friendly

Viewport not configured correctly
Consider using the following viewport settings to ensure that your page works well on mobile devices <meta name="viewport" content="width=device-width, initial-scale=1">
```

I cannot judge if that's relevant or not...

**Comment by lucadelu** [comment]
The line is already in the [right place](https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/partials/head.html#L11)  but it is duplicated in the [following line](https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/partials/head.html#L12) with an extra value

**Comment by nbozon** [comment]
This should be fixed now (the meta tag was indeed duplicated, only one is remaining now in master)

Bing mobile test is still complaining on index (cache?) but passing on other pages  :astonished:

Google mobile test passing:  :smiley:
https://search.google.com/test/mobile-friendly?id=-SjilGvTzNrEZ-YhayEkXA

**Comment by neteler** [comment]
I checked it again with
- Google indexing: https://search.google.com/search-console?resource_id=https://staging.grass.osgeo.org/
- Bing indexing: https://www.bing.com/webmaster/home/dashboard?url=https%3A%2F%2Fstaging.grass.osgeo.org%2F

Looks good, thanks for the fix!
