### ISSUE TITLE
Remove Calgary entry from main page

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#184]
In the main landing page still the unfortunately cancelled Calgary 2020 conf is listed:

https://github.com/OSGeo/grass-website/blob/9d46e83b8597a2f6621068363e0b715cf0b35363/themes/grass/layouts/partials/foss4g.html#L2

It should be replaced with another (online) event, e.g. chosen from https://www.osgeo.org/events/

**Comment by lucadelu** [comment]
Right now I don't see any event really relevant (the only close is FOSS4G oceania but at this moment the program is wrong and it show the sotm 2020 program :-/)... probably we could also leave blank the card

**Comment by veroandreo** [comment]
I think we should leave it blank now. FOSS4G 2021 committee is now deciding on the logo for the event, we can add it once we have a winner

**Comment by nbozon** [comment]
Done - 

The [foss4g.html partial](https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/partials/foss4g.html) has been edited and now shows a "coming soon" message, as follows:

<img width="293" alt="Capture d’écran 2020-07-23 à 12 22 52" src="https://user-images.githubusercontent.com/7135374/88276438-57bd0480-ccdf-11ea-8245-bf9a89160af3.png">

To be updated when the next event will be known 👍 

Closing -
