### ISSUE TITLE
Open external links in new tabs/windows

### ISSUE THREAD

**Issue by CarlosGrohmann** [OSGeo/grass-website#185]
As a suggestion, I think that opening external links (wiki, mailing list, youtube, etc) should be on new tabs/windows. I'm not sure how to automatically do it with Hugo, but for Jekyll there is a plugin that does that when the site is built so there's probably something in the same lines for Hugo

**Comment by veroandreo** [comment]
I fully agree with this. @nbozon, could you take a look at this too?

**Comment by nbozon** [comment]
This is now implemented in master -

All external link (using domain name different than {{ .Site.BaseURL }} ) now get a class named ".ext" and open in a new tab.

Done with JavaScript in [script.js](https://github.com/OSGeo/grass-website/blob/master/themes/grass/assets/js/script.js), as follows:

    $( 'a' ).each(function() {
        if( location.hostname === this.hostname || !this.hostname.length ) {
          $(this).addClass('int');
       } else {
          $(this).addClass('ext');
           $(this).attr({
              target: "_blank",
               title: $(this).text()
            });
       }
    });

Closing -
