### ISSUE TITLE
move "community" to "contribute" (??) and add search for mailing lists

### ISSUE THREAD

**Issue by CarlosGrohmann** [OSGeo/grass-website#187]
Ok, two ideas here:

1 - move "community" to other menu, or maybe just the mailing lists (as they are more related to "learn")

2 - add search form for the mailing lists. So far, only the subscription page is reached through the links

**Comment by neteler** [comment]
re: 2 - add search:

Do you mean to have search as it was done here: https://grass.osgeo.org/documentation/search-engine/ (via Google)?

**Comment by CarlosGrohmann** [comment]
Yes, that's the idea (except maybe for the 'clear' button...)

**Comment by nbozon** [comment]
1) Menus are now somehow fixed, and we do not want to change them too often, nor adding additional sub menus.

2) It was previously asked to remove any request to Google, to avoid users being tracked when visiting the website.
Adding a google search form would make this effort useless, so i'm not in favor of adding it.

Closing this one for now -
