### ISSUE TITLE
Download source code

### ISSUE THREAD

**Issue by micha-silver** [OSGeo/grass-website#190]
IMHO. there should be an entry on the Download dropdown menu to the "GRASS GIS source code" link.

**Comment by veroandreo** [comment]
See also #195

**Comment by nbozon** [comment]
There are already too many submenu entries,  and we should avoid to add more at this stage.
And source code is visible enough imo:
A link to source code is already available in the footer of every page (https://github.com/OSGeo/grass).
A dedicated subsection is also linking to source code, at the bottom of the [Download page](https://staging.grass.osgeo.org/download/) itself.
Closing for now, please reopen if necessary

**Comment by mlennert** [comment]
I don't agree with this reasoning. For me, easily locatable source code is a must for a GPL project. We should at least have the link to the github clearly marked. Could one entry to the 'Download' menu be a direct link to the repository ?

**Comment by neteler** [comment]
We may simplify the download menu into, e.g.,

- GRASS GIS installers
- GRASS GIS source code
- Docker images
- Addons
- Sample data

**Comment by veroandreo** [comment]
> I don't agree with this reasoning. For me, easily locatable source code is a must for a GPL project. We should at least have the link to the github clearly marked. Could one entry to the 'Download' menu be a direct link to the repository ?

I think this is, at this point, the easiest solution, just one more entry (*Source code*) in the Download menu that points directly to the github repo of grass (we don't need to create a new page). @neteler's suggestion is nice but it would imply a re-design/merge of linux, windows and mac pages

**Comment by neteler** [comment]
Suggestion: move "source code" entry on page https://staging.grass.osgeo.org/download/ to the top, rather than hard-to-reach bottom...

**Comment by lucadelu** [comment]
> > I don't agree with this reasoning. For me, easily locatable source code is a must for a GPL project. We should at least have the link to the github clearly marked. Could one entry to the 'Download' menu be a direct link to the repository ?
> 
> I think this is, at this point, the easiest solution, just one more entry (_Source code_) in the Download menu that points directly to the github repo of grass (we don't need to create a new page). @neteler's suggestion is nice but it would imply a re-design/merge of linux, windows and mac pages

Probably could be better to link the [wiki page](https://grasswiki.osgeo.org/wiki/Compile_and_Installl)

**Comment by lucadelu** [comment]
> Suggestion: move "source code" entry on page https://staging.grass.osgeo.org/download/ to the top, rather than hard-to-reach bottom...

I don't know, depending on target.. do we want to attract normal user or power user/developer ?

**Comment by mlennert** [comment]
On 28/07/20 07:08, Luca Delucchi wrote:
>         I don't agree with this reasoning. For me, easily locatable
>         source code is a must for a GPL project. We should at least have
>         the link to the github clearly marked. Could one entry to the
>         'Download' menu be a direct link to the repository ?
> 
>     I think this is, at this point, the easiest solution, just one more
>     entry (/Source code/) in the Download menu that points directly to
>     the github repo of grass (we don't need to create a new page).
>     @neteler <https://github.com/neteler>'s suggestion is nice but it
>     would imply a re-design/merge of linux, windows and mac pages
> 
> Probably could be better to link the wiki page 
> <https://grasswiki.osgeo.org/wiki/Compile_and_Installl>

https://grasswiki.osgeo.org/wiki/Compile_and_Install

would be better ;-)

But then this page would have to be updated: "Download GRASS GIS source 
code" links to https://grass.osgeo.org/download/software/sources/ which 
is dead.

I believe the github is the surest place if we want it to always be up 
to date...

Maybe the README.md page of the github could be made more newbie 
friendly, i.e. include a short intro to grass and a link to some 
resources (besides the website obviously).

**Comment by hellik** [comment]
>I believe the github is the surest place if we want it to always be up
>to date...

I agree here with Moritz, just link to github. and keep gh uptodate.

**Comment by veroandreo** [comment]
> > I believe the github is the surest place if we want it to always be up
> > to date...
> 
> I agree here with Moritz, just link to github. and keep gh uptodate.

I agree as well. For a start, I moved the link to source code to the top of download page in #215

**Comment by neteler** [comment]
If @micha-silver agrees, we might close this report as done.

**Comment by micha-silver** [comment]
Fine with me, thanks
