### ISSUE TITLE
Broken page headers

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#205]
Check the rendered source code, it doesn't look healthy yet to me:

view-source:https://grass.osgeo.org/

```
<!DOCTYPE html>
<html>
<head>                   <<---?
  <title></title>                   <<---?
</head>                   <<---?
<body>                   <<---?
  <!DOCTYPE html>                   <<---?
<html  lang="en-us">

<head>                   <<---?
  <meta charset="utf-8">
  <title>GRASS GIS - Bringing advanced geospatial technologies to the world</title>
```

Somewhere in the template the broken header leaks in.

**Comment by nbozon** [comment]
Oops ! 
This is now fixed in master, and default markup was also cleaned a bit on the way.
@neteler @lucadelu can you check and close this ticket please ? thx

**Comment by neteler** [comment]
Thanks for having fixed the header (for reference: 77f6f87c415798f4cf10b650a2c5f86e13c8eb6d and fc9532f204e964d8d9e1f317a68b3eb30c7b4b05)

Still the validator shows some tag issues:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fgrass.osgeo.org%2F

**Comment by neteler** [comment]
In addition, there still seems to be a difference with the header (I don't know how this technically works):

- the old site (now at https://old.grass.osgeo.org/) delivers a "preview":
![image](https://user-images.githubusercontent.com/1295172/88664132-dc8f9000-d0dc-11ea-84d2-507a71f0a590.png)

- the new site does not:
![image](https://user-images.githubusercontent.com/1295172/88664149-e44f3480-d0dc-11ea-8e07-151ac40569a6.png)

Could this be fixed, @nbozon ?

**Comment by veroandreo** [comment]
I tried adding 
```
<meta name="description" content="{{if .IsHome}}{{ $.Site.Params.description }}{{else}}{{.Description}}{{end}}" />
```
in the `themes/grass/layouts/partials/head.html` file as suggested in [hugo docs](https://gohugo.io/variables/site/), but the landing page source code does not get the description provided in #210. The other option is to just write the description directly in the <meta> tag of `head.html`

**Comment by mlennert** [comment]
> I tried adding
> 
> ```
> <meta name="description" content="{{if .IsHome}}{{ $.Site.Params.description }}{{else}}{{.Description}}{{end}}" />
> ```
> 
> in the `themes/grass/layouts/partials/head.html` file as suggested in [hugo docs](https://gohugo.io/variables/site/), but the landing page source code does not get the description provided in #210. The other option is to just write the description directly in the `<meta>` tag of `head.html`

Try something a bit more generic:

 {{ if .Params.description }}
<meta name="description" content="{{ .Params.description }}">
{{ else if .Site.Params.description }}
<meta name="description" content="{{ .Site.Params.description }}">
{{ end }}

Seems to work for me locally.

**Comment by neteler** [comment]
> In addition, there still seems to be a difference with the header (I don't know how this technically works):
> 
>     * the old site (now at https://old.grass.osgeo.org/) delivers a "preview":
>       ![image](https://user-images.githubusercontent.com/1295172/88664132-dc8f9000-d0dc-11ea-84d2-507a71f0a590.png)
> 
>     * the new site does not:
>       ![image](https://user-images.githubusercontent.com/1295172/88664149-e44f3480-d0dc-11ea-8e07-151ac40569a6.png)
> 
> 
> Could this be fixed, @nbozon ?

... still not working.

**Comment by mlennert** [comment]
> > In addition, there still seems to be a difference with the header (I don't know how this technically works):
> > ```
> > * the old site (now at https://old.grass.osgeo.org/) delivers a "preview":
> >   ![image](https://user-images.githubusercontent.com/1295172/88664132-dc8f9000-d0dc-11ea-84d2-507a71f0a590.png)
> > 
> > * the new site does not:
> >   ![image](https://user-images.githubusercontent.com/1295172/88664149-e44f3480-d0dc-11ea-8e07-151ac40569a6.png)
> > ```
> > 
> > 
> > Could this be fixed, @nbozon ?
> 
> ... still not working.

Where do you see these previews ?

**Comment by neteler** [comment]
> Where do you see these previews ?

E.g. in telegram

**Comment by mlennert** [comment]
I see the preview correctly in Skype & WhatsApp. In Telegram, I think you have to explicitly activate such previews in the security settings. So, are you sure this isn't  a specific Telegram issue ?

**Comment by neteler** [comment]
Well, https://old.grass.osgeo.org/ works nicely...

**Comment by mlennert** [comment]
On 29/07/20 11:01, mlennert wrote:
>
> AFAICT, previews are generated on the Telegram servers. So maybe they 
> just haven't caught up with last night's changes, yet ?
>
> —
>

Try now. I used 
https://telegramgeeks.com/2016/03/you-can-update-link-preview-telegram/

**Comment by nbozon** [comment]
I've improved the metatags for social as follow:

      <meta name="keywords" content="{{.Site.Params.Keywords }}">
      <meta property="og:url" content="{{.Site.BaseURL}}">
      <meta property="og:image" content="{{.Site.BaseURL}}images/other/share-img.png">
      <meta property="og:title" content="{{ .Site.Title }}">
      <meta property="og:description" content="{{ .Site.Params.description }}">
      <meta name="twitter:card" content="GRASS GIS">
      <meta name="twitter:site" content="@GRASSGIS">
      <meta name="twitter:creator" content="@GRASSGIS">
      <meta name="twitter:title" content="{{ .Site.Title }}">
      <meta name="twitter:description" content="{{ .Site.Params.description }}">

Is it better now @neteler @mlennert ?
Previews should now use Tile, Description and [Share image](https://grass.osgeo.org/images/other/share-img.png).

For Twitter, the @GRASSGIS account owner shoudl create a [Twitter card ](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/abouts-cards) named **GRASS GIS** .

BTW, let me suggest to update the header images on the project soicla accounts with the image bellow, as that would help to maximize impact of the new design.
![GRASS_GIS_new_website](https://user-images.githubusercontent.com/7135374/88782176-91818580-d18d-11ea-8ef9-86bb5f119156.png)

**Comment by nbozon** [comment]
https://socialsharepreview.com/?url=https://grass.osgeo.org/.  @neteler @mlennert @veroandreo

**Comment by neteler** [comment]
Telegram now works as well, great:
![image](https://user-images.githubusercontent.com/1295172/88783683-6435d700-d18f-11ea-849e-410790cecd9e.png)

**Comment by neteler** [comment]
Good work! Now only a few warning are left:

https://validator.w3.org/nu/?doc=https%3A%2F%2Fgrass.osgeo.org%2F

**Comment by neteler** [comment]
There is still something weird:

Try https://www.google.com/search?client=firefox-b-d&q=grass+gis

![image](https://user-images.githubusercontent.com/1295172/89128154-d9890b00-d4f3-11ea-9a12-6516a0be9631.png)

**Comment by nbozon** [comment]
This is now fixed in master, as follows:

     <meta name="description" content="{{ if .Params.summary }}{{ .Params.summary }}{{ else if .Site.Params.Description }}{{ .Site.Params.Description }}{{ end }}" />

If the md file used for generating the page has a summary, its value is used as page meta description, otherwise the general description defined in config.toml is used by default.

Looks good now when you search "GRASS GIS" in Google:

[<img width="408" alt="Capture d’écran 2020-09-17 à 10 49 15" src="https://user-images.githubusercontent.com/7135374/93448051-74d31580-f8d3-11ea-8a24-6324d9089fe8.png">](https://www.google.com/search?q=grass+gis&rlz=1C5CHFA_enFR765FR770&oq=GRASS+GIS&aqs=chrome.0.35i39l2j0l3j69i60l3.3000j0j7&sourceid=chrome&ie=UTF-8)

@neteler please check and close this issue, thx !

**Comment by veroandreo** [comment]
Looks good to me. It's on us then to tweak different pages' descriptions. 
Thanks @nbozon :+1:

**Comment by neteler** [comment]
Thanks a lot, @nbozon !

**Comment by neteler** [comment]
> If the md file used for generating the page has a summary, its value is used as page meta description, otherwise the general description defined in config.toml is used by default.

... respective note added to README.md in a462a244756e451402a4a88f4520bf7c9599d8fb
