### ISSUE TITLE
Add sitemap

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#21]
At time the new site is missing (AFAIK) a sitemap:

https://gohugo.io/templates/sitemap-template/

This is important to be properly indexed by search engines. Please add it.

**Comment by neteler** [comment]
ping

**Comment by nbozon** [comment]
The default builtin sitemap functionality has bee added to the config.toml with default params, as follow:

    [sitemap]
      changefreq = "monthly"
      filename = "sitemap.xml"
      priority = 0.5

The compliant sitemap XML file is now generated at the root of the site directory
http://staging.grass.osgeo.org/sitemap.xml

To be used by all kind of robots :)

**Comment by neteler** [comment]
Great, thanks!
