### ISSUE TITLE
Site announcement news ignored by hugo and not rendered!

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#216]
While it sounds rediculous, hugo doesn't render this page:

https://github.com/OSGeo/grass-website/blob/master/content/news/2020_07_29_new_website_and_bday.md

--> missing here: https://grass.osgeo.org/news/

Why is that? **Today** is the release day... any ideas @mlennert @lucadelu @nbozon ?

**Comment by nbozon** [comment]
Hugo is clever and won't render news item before the set date and time 🕐   !  (server time)
<img width="316" alt="Capture d’écran 2020-07-29 à 09 59 20" src="https://user-images.githubusercontent.com/7135374/88773590-9856cb00-d182-11ea-883e-c0369c76974e.png">
Fixed and building now:
https://grass.osgeo.org/news/2020_07_29_new_website_and_bday/

Closing -
