### ISSUE TITLE
Privacy error for mapskin icon link

### ISSUE THREAD

**Issue by baharmon** [OSGeo/grass-website#218]
The link for the full icon list of mapskin on https://grass.osgeo.org/about/theme/ reports a privacy error on Chrome. I suggest changing the link from `https://mapsk.in/#icons` to just `http://mapsk.in/`.

**Comment by neteler** [comment]
Yeah, same on Firefox. The reason is this: https://mapsk.in uses the certificate of github... :

```
Websites prove their identity via certificates. Firefox does not trust this site because it uses 
a certificate that is not valid for mapsk.in.
The certificate is only valid for the following names: *.github.com, github.com
 
Error code: SSL_ERROR_BAD_CERT_DOMAIN
```

While that's a mapsk problem, we need to understand how to deal with that.
Do you have any suggestions, @nbozon ?

**Comment by nbozon** [comment]
Thx for the report. Indeed, this was not related to the GRASS website source code.
Fixed on the mapsk.in side (updated DNS with correct github page IPs, renew SSL cert and remove mixed content). 
https://mapsk.in/#icons works correctly again
Closing -
