### ISSUE TITLE
create a DNS record for www.grass.osgeo.org

### ISSUE THREAD

**Issue by pesekon2** [OSGeo/grass-website#219]
If you go to the GRASS website the lazy way without typing `www` (<grass.osgeo.org>), you will load the page without a problem. However, if you want to try it with `www` (<www.grass.osgeo.org>), you'll get the `Page not found` error message.

The reason is that we do not have a DNS record for that.

> EDIT: Both tags `bug` and `enhancement` are added as for some it is something that they would expect to work, for some something extra.

**Comment by neteler** [comment]
I am -0 on that:

- www in addition is increasing the confusion of which server URL is official
- it does not add any value

I could change my opinion to +0 if it is a redirect from www.grass.osgeo.org to grass.osgeo.org.

**Comment by hellik** [comment]
I second here @neteler 

I see no added value by adding www.

**Comment by nilason** [comment]
Why not redirect both www.grass.osgeo.org and grass.osgeo.org to https://grass.osgeo.org.

See e.g.: qgis.org and http://www.qgis.org/

**Comment by jmckenna** [comment]
All it takes is one referrer (webpage that links to GRASS site) run by an old-school admin (there are many still) who includes 'www' in the link.  +1 to this change.

**Comment by nilason** [comment]
Wouldn't apache `mod_rewrite` do the job?

**Comment by robe2** [comment]
Should be resolved at - https://trac.osgeo.org/osgeo/ticket/2495

just redirected  www.grass.osgeo.org and grass.osgeo.org to https://grass.osgeo.org.

**Comment by neteler** [comment]
Thanks so much, @robe2 ! Works smoothly.
