### ISSUE TITLE
Complete rsync support

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#22]
I have just completed the `rsync` setup for our mirrors on the new GRASS GIS Web site (currently https://staging.grass.osgeo.org/). Being behind a firewall, it is not yet visible. But as soon as we switch the old and new server, this should then work:

# soon visible:
rsync grass.osgeo.org::grass-website

Note to self: notify our South African mirror (https://lists.osgeo.org/pipermail/grass-web/2020-February/date.html) once the DNS switch has been completed.

**Comment by neteler** [comment]
Thanks to Regina from OSGeo-SAC the rsync support for mirroring is ready:

```
rsync --port=50026 staging.grass.osgeo.org::
```

Please try it out.

TODO: document this mirroring option to a page in the new website.

**Comment by neteler** [comment]
Open issue:

While
`path=/var/www/html/`

we do have the software packages in
`/var/www/code_and_data/`

which are linked into `/var/www/html/`. AKAIK rsync will not follow the links, hence the  `/var/www/code_and_data/` will not be available for mirroring. How to solve that?

**Comment by landam** [comment]
> `rsync --port=50026 staging.grass.osgeo.org::`

@neteler I tried this command, but nothing has been mirrored.

```
time rsync --port=50026 staging.grass.osgeo.org::
GRASS GIS Website

grass-website  	GRASS GIS Website

real	0m0.481s
user	0m0.002s
sys	0m0.000s

ls grass-website
ls: cannot access 'grass-website': No such file or directory
```
?

**Comment by neteler** [comment]
I think you have ssh access, do you see the mistake in the config?

**Comment by landam** [comment]
> > `rsync --port=50026 staging.grass.osgeo.org::`
> 
> @neteler I tried this command, but nothing has been mirrored.

command below works

```
rsync -az --port=50026 staging.grass.osgeo.org::grass-website grass-website
```

**Comment by mlennert** [comment]
> > > `rsync --port=50026 staging.grass.osgeo.org::`
> > 
> > 
> > @neteler I tried this command, but nothing has been mirrored.
> 
> command below works
> 
> ```
> rsync -az --port=50026 staging.grass.osgeo.org::grass-website grass-website
> ```

Does this proposed solution solve the issue ?

**Comment by neteler** [comment]
AFAIK it doesn't since the links aren't followed

**Comment by mlennert** [comment]
On 20/05/20 17:30, Markus Neteler wrote:
> AFAIK it doesn't since the links aren't followed

Even with rsync -az ?

-a implies -l

and

-l 'copy symlinks as symlinks'

Or is the problem that the data the symlinks point to isn't transferred ?

**Comment by neteler** [comment]
> On 20/05/20 17:30, Markus Neteler wrote: AFAIK it doesn't since the links aren't followed
> Even with rsync -az ?
> […](#)
> -a implies -l and
> -l 'copy symlinks as symlinks' Or is the problem that the data the symlinks point to isn't transferred ?

It looks like that: -l might be the problem, as we want the content, not the symlinks:

```

On 20/05/20 17:30, Markus Neteler wrote:
 AFAIK it doesn't since the links aren't followed
Even with rsync -az ?
…
rsync -az --port=50026 staging.grass.osgeo.org::grass-website grass-website
...
lrwxrwxrwx   1 mneteler mneteler     35 May  8 21:22 programming7 -> /var/www/code_and_data/programming7
drwxr-xr-x 120 mneteler mneteler  12288 May  8 22:00 news/
lrwxrwxrwx   1 mneteler mneteler     33 May  9 00:28 robots.txt -> /var/www/code_and_data/robots.txt
lrwxrwxrwx   1 mneteler mneteler     33 May  9 00:29 sampledata -> /var/www/code_and_data/sampledata
lrwxrwxrwx   1 mneteler mneteler     35 May  9 00:30 history_docs -> /var/www/code_and_data/history_docs
…

... of course all broken.

**Comment by mlennert** [comment]
On 20/05/20 23:55, Markus Neteler wrote:
>     On 20/05/20 17:30, Markus Neteler wrote: AFAIK it doesn't since the
>     links aren't followed
>     Even with rsync -az ?
>     … <#>
>     -a implies -l and
>     -l 'copy symlinks as symlinks' Or is the problem that the data the
>     symlinks point to isn't transferred ?
> 
> It looks like that: -l might be the problem, as we want the content, not 
> the symlinks:
> 
> |On 20/05/20 17:30, Markus Neteler wrote: AFAIK it doesn't since the 
> links aren't followed Even with rsync -az ? … rsync -az --port=50026 
> staging.grass.osgeo.org::grass-website grass-website ... lrwxrwxrwx 1 
> mneteler mneteler 35 May 8 21:22 programming7 -> 
> /var/www/code_and_data/programming7 drwxr-xr-x 120 mneteler mneteler 
> 12288 May 8 22:00 news/ lrwxrwxrwx 1 mneteler mneteler 33 May 9 00:28 
> robots.txt -> /var/www/code_and_data/robots.txt lrwxrwxrwx 1 mneteler 
> mneteler 33 May 9 00:29 sampledata -> /var/www/code_and_data/sampledata 
> lrwxrwxrwx 1 mneteler mneteler 35 May 9 00:30 history_docs -> 
> /var/www/code_and_data/history_docs … ... of course all broken. |
> 

Have you tried with -L, then ?
I.e. if you want to do -a, this would mean something like:

rsync -rLptgoDz

?

Another option would be to use two different rsync calls to rsync the 
different parts of the directory tree, i) web site ii) data. This would 
make sense especially if one changes with a very different frequency 
than the other.

Moritz

**Comment by neteler** [comment]
>  -rLptgoDz

With that I get:

```
....
symlink has no referent: "/grass75" (in grass-website)
symlink has no referent: "/grass32" (in grass-website)
symlink has no referent: "/grass77" (in grass-website)
....
```

**Comment by mlennert** [comment]
> >  -rLptgoDz
> 
> With that I get:
> 
> ```
> ....
> symlink has no referent: "/grass75" (in grass-website)
> symlink has no referent: "/grass32" (in grass-website)
> symlink has no referent: "/grass77" (in grass-website)
> ....
> ```

That sounds like the destination of the links doesn't exist in your source...

**Comment by neteler** [comment]
Ok, I am a bit confused here. To summarize, the current situation:

```
# rsync exposed directory:
grep path /etc/rsyncd.conf 
path=/var/www/

# the two directories:
ls -la /var/www/
drwxr-xr-x 44 neteler users 46 May  8 22:33 code_and_data/
drwxr-xr-x 14 neteler users 63 May 22 15:15 html/
```

Aim: let `/var/www/html/grass*` point to the respective directories in `/var/www/code_and_data/grass*`, through links.

Question: shall that be relative or absolute paths?

**Comment by neteler** [comment]
It seems to work now, but pls verify if all is there:

- https://grass.mirror.download.it/
- another mirror exists in South Africa (TODO: URL)

**Comment by ninsbl** [comment]
It seems (svg?) icons, e.g. on the main page on that mirror are not displayed properly (at least on mobile (firefox)).

**Comment by neteler** [comment]
With the Firefoe "inspect element" I see on https://grass.mirror.download.it/:

```
Source map error: Error: request failed with status 404
Resource URL: https://staging.grass.osgeo.org/plugins/bootstrap/bootstrap.min.css
```

Maybe that be a cross-linking issue? Hardcoded server URL to be removed?

**Comment by mlennert** [comment]
> With the Firefoe "inspect element" I see on https://grass.mirror.download.it/:
> 
> ```
> Source map error: Error: request failed with status 404
> Resource URL: https://staging.grass.osgeo.org/plugins/bootstrap/bootstrap.min.css
> ```
> 
> Maybe that be a cross-linking issue? Hardcoded server URL to be removed?

The hardcoded link seems to be created at site build time in

- themes/grass/layouts/partials/footer.html
- themes/grass/layouts/partials/head.html

based on this template:
```
 <link rel="stylesheet" href="{{ .Site.BaseURL }}plugins/bootstrap/bootstrap.min.css">
```
I don't know how to code this as a relative path, knowing that the header and footer are used at different depths within the site and so the relative path has to be different for each generated page.

This raises the question: wouldn't it be easier for mirror sites to just clone the github and build with hugo instead of rsyncing the built website ? Possibly just rsyncing the code_and_data directory ?

**Comment by neteler** [comment]
> > With the Firefoe "inspect element" I see on https://grass.mirror.download.it/:
> > ```
> > Source map error: Error: request failed with status 404
> > Resource URL: https://staging.grass.osgeo.org/plugins/bootstrap/bootstrap.min.css
> > ```
> > 
> > 
> > Maybe that be a cross-linking issue? Hardcoded server URL to be removed?
> 
> The hardcoded link seems to be created at site build time in
> 
>     * themes/grass/layouts/partials/footer.html
> 
>     * themes/grass/layouts/partials/head.html
> 
> 
> based on this template:
> 
> ```
>  <link rel="stylesheet" href="{{ .Site.BaseURL }}plugins/bootstrap/bootstrap.min.css">
> ```
> 
> I don't know how to code this as a relative path, knowing that the header and footer are used at different depths within the site and so the relative path has to be different for each generated page.

@nbozon can the absolute URL be avoided?

If not, it could still be mangled while copying the generated site to the target HTML directory on the server.

> This raises the question: wouldn't it be easier for mirror sites to just clone the github and build with hugo instead of rsyncing the built website ? Possibly just rsyncing the code_and_data directory ?

The chance that mirror site owners implement a GH-clone + hugo chain is close to zero in my view...

**Comment by mlennert** [comment]
Actually, any idea why there was a 404 error on https://staging.grass.osgeo.org/plugins/bootstrap/bootstrap.min.css ? For me it works ?

**Comment by neteler** [comment]
It works there but it doesn't here: https://grass.mirror.download.it/

**Comment by mlennert** [comment]
Actually, I see the same 404 errors in the original site, so I don't think these are the issue. I rather have the feeling that it might be a [Cross-Origin Request](https://developer.mozilla.org/fr/docs/Web/HTTP/CORS/Errors/CORSAllowOriginNotMatchingOrigin) issue linked to fontawesome.

**Comment by mlennert** [comment]
And here's the related error message in the dev console: 
```
Cross-Origin Request Blocked: 
The Same Origin Policy disallows reading the remote resource at https://staging.grass.osgeo.org/plugins/open-sans/fonts/opensans-regular-webfont.woff. 
(Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://staging.grass.osgeo.org’).
```

**Comment by mlennert** [comment]
I'm moving on unknown territory, here, but IIUC, there are two solutions:

1. Make the links relative so that each mirror points to its own resources (which are in the 'plugins' directory.
2. Change the web server settings on the original website's server to include the Access-Control-Allow-Origin header for webfonts.

Probably, 1 is cleaner, but no idea how to make this happen. So, let's see what @nbozon has to say.

**Comment by mlennert** [comment]
BTW, AFAICS, this is the last real blocker for the public release of the website...

**Comment by mlennert** [comment]
> I'm moving on unknown territory, here, but IIUC, there are two solutions:
> 
>     1. Make the links relative so that each mirror points to its own resources (which are in the 'plugins' directory.
> 
>     2. Change the web server settings on the original website's server to include the Access-Control-Allow-Origin header for webfonts.
> 
> 
> Probably, 1 is cleaner, but no idea how to make this happen. So, let's see what @nbozon has to say.

@nbozon, can you help us with this ? If not, please let us know, so we do not wait for your answer.

**Comment by mlennert** [comment]
> The chance that mirror site owners implement a GH-clone + hugo chain is close to zero in my view...

Maybe we could discuss it with them ?

**Comment by neteler** [comment]
> > The chance that mirror site owners implement a GH-clone + hugo chain is close to zero in my view...
> 
> Maybe we could discuss it with them ?

I have no energy for that, sorry...

**Comment by mlennert** [comment]
On 20/06/20 11:26, Markus Neteler wrote:
>         The chance that mirror site owners implement a GH-clone + hugo
>         chain is close to zero in my view...
> 
>     Maybe we could discuss it with them ?
> 
> I have no energy for that, sorry...
> 

Is there a list of mirror contacts somewhere ?

Moritz

**Comment by neteler** [comment]
Yes, I always cc'ed the grass-website mailing list.

**Comment by nbozon** [comment]
@mlennert i don't know what's the problem with rsync and have very little experience with mirroring, so please do not wait my answer to investigate ! i'm not the sysadmin, only the designer :) 

It appears that only webfonts  are missing on mirrored sites, for example in https://grass.mirror.download.it/ i can see open-sans, font-awesome, mapskin and all other fonts in use are not rendered.  

**This possibly means that support for ttf/svg/ot/woff/woff2 is not available on the mirror server.**

Similar problem actually happened when we initially deployed the new website on OSGeo server @neteler , and Regina from SAC had to add the needed mime-types to  the nginx config there
(see https://github.com/OSGeo/grass-website/issues/20 and https://trac.osgeo.org/osgeo/ticket/2427 for reference)
I have the feeling that the same his happening on mirrors, but i'm may be wrong.

**Comment by nbozon** [comment]
The CORS errors may confirm the unsupported fonts problem.
I think we should first ensure that the mirror server is sending the correct Access-Control-Allow-Origin header when font files are requested, and ask for the sysadmins to modify their setup if needed.

For Apache server, this should do the trick:

     <FilesMatch ".(eot|otf|ttf|woff|woff2)">
      Header always set Access-Control-Allow-Origin "*"
     </FilesMatch> 

For Nginx server:

     location ~* \.(eot|otf|ttf|woff|woff2)$ {
        add_header Access-Control-Allow-Origin *;
     }

@mlennert could you please contact mirror servers sysadmins and ask them to check their headers if possible ? Thx in advance -

**Comment by mlennert** [comment]
On 22/06/20 07:23, Nicolas Bozon wrote:
>
> The CORS errors may confirm the unsupported fonts problem.
> I think we should first ensure that the mirror server is sending the 
> correct Access-Control-Allow-Origin header when font files are 
> requested, and ask for the sysadmins to modify their setup if needed.
>
> For Apache server, this should do the trick:
>
> |<FilesMatch ".(eot|otf|ttf|woff|woff2)"> Header always set 
> Access-Control-Allow-Origin "*" </FilesMatch> |
>
> For Nginx server:
>
> |location ~* \.(eot|otf|ttf|woff|woff2)$ { add_header 
> Access-Control-Allow-Origin *; } |
>
> @mlennert <https://github.com/mlennert> could you please contact 
> mirror servers sysadmins and ask them to check their headers if 
> possible ?
>
>
I can contact them, but are you sure that these server side 
configurations have to be set on the server serving the page, and not 
the server serving the font ?

**Comment by mlennert** [comment]
> I can contact them, but are you sure that these server side configurations have to be set on the server serving the page, and not the server serving the font ?

Reading some more on the subject, I'm pretty convinced that the config has to be changed on our side. I've posted the question at https://trac.osgeo.org/osgeo/ticket/2427#comment:5.

**Comment by mlennert** [comment]
Futher discussion on the Font Awesome cross-origin issue is at #172.

**Comment by neteler** [comment]
Also the icons are available now, again pls verify if all is there:

- https://grass.mirror.download.it/ (Italy)
- https://grass.mirror.ac.za/ (South Africa)

If yes, we may close this issue.

**Comment by veroandreo** [comment]
Seems all is there

**Comment by lucadelu** [comment]
For me they are not working 

![Screenshot from 2020-06-29 21-57-46](https://user-images.githubusercontent.com/178741/86050117-9bf81480-ba53-11ea-96ea-430865e0c241.png)

**Comment by lucadelu** [comment]
Update, only Firefox is broken, Chromium is work fine. Probably is due to some security setting.

Closing

**Comment by mlennert** [comment]
> Update, only Firefox is broken, Chromium is work fine. Probably is due to some security setting.
> 
> Closing

For me it works perfectly in Firefox on Debian testing:
![screenshot_20200630_161710](https://user-images.githubusercontent.com/13900290/86137284-66a00500-baed-11ea-89e9-8733464bb8e4.png)
