### ISSUE TITLE
What is GRASS GIS?

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#227]
Seems we lack a few sentences in "About"... at least I couldn't find any one-liner on the new site.

It could be something like this:

## About GRASS GIS

The Geographic Resources Analysis Support System (https://grass.osgeo.org/), commonly referred to as GRASS GIS, is an Open Source Geographic Information System providing powerful raster, vector and geospatial processing capabilities. It can be used either as a stand-alone application or as backend for other software packages such as QGIS and R geostatistics or in the cloud. It is distributed freely under the terms of the GNU General Public License (GPL). GRASS GIS is a founding member of the Open Source Geospatial Foundation (OSGeo).

**Comment by lucadelu** [comment]
Are you speaking about [this page](https://grass.osgeo.org/about/)?

**Comment by neteler** [comment]
That would be ideal, yes.

**Comment by neteler** [comment]
Solved & thanks
