### ISSUE TITLE
Broken link to Windows Add-ons (in old site)

### ISSUE THREAD

**Issue by NikosAlexandris** [OSGeo/grass-website#23]
This link [https://wingrass.fsv.cvut.cz/grass74/x86_64/addons/latest/logs/](https://wingrass.fsv.cvut.cz/grass74/x86_64/addons/latest/logs/) labeled as **Windows** in [Add-ons](https://grass.osgeo.org/download/addons/), in the _old_ site, is broken and outdated too. While the migration is on-going, I guess this will be taken care in the new site.

**Comment by neteler** [comment]
It seems that there is no summay.html page generated for G7 addons...

**Comment by neteler** [comment]
Found it at https://wingrass.fsv.cvut.cz/grass78/x86_64/addons/latest/logs/

Old CMS page is fixed.
