### ISSUE TITLE
OSGeo4W: add more installation instructions?

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#232]
The current installation instructions at
https://grass.osgeo.org/download/windows/#OSGeo4W

are probably too limited for new users.

Compare the longer instructions on the old site:
https://old.grass.osgeo.org/download/software/ms-windows/#osgeo4w
which offer insights on _Express Desktop Install_  and _Advanced Install_ ...

How about a (new) Wiki page with more details, then to be linked?

**Comment by veroandreo** [comment]
I had written instructions for the *Advanced install* here: https://gitpitch.com/veroandreo/grass-gis-conae/master?p=slides/00_installation&grs=gitlab#/3

I can help with the wiki page, but I would need updated screenshots. No windows box here to re-create them. Also, please check the steps, maybe some dependencies are now automatically fetched.

**Comment by neteler** [comment]
Your slides are pretty nice!

Meanwhile I have updated the totally outdated wiki page and created/added screenshots:

https://grasswiki.osgeo.org/wiki/Installation_Guide#OSGeo4W_installer

Feel free to improve it...

**Comment by hellik** [comment]
> maybe some dependencies are now automatically fetched.

dependencies automatically downloaded are listed here: 

http://download.osgeo.org/osgeo4w/x86_64/release/grass/grass/setup.hint

python related are:

- python3-gdal 
- python3-matplotlib 
- python3-wx 
- python3-numpy 
- python3-pillow 
- python3-pip 
- python3-ply 
- python3-pyopengl  
- python3-psycopg2 
- python3-six 
- python3-pywin32

all other useful python packages have to be activated manually.

**Comment by hellik** [comment]
> 
> 
> The current installation instructions at
> https://grass.osgeo.org/download/windows/#OSGeo4W
> 
> are probably too limited for new users.
> 
> Compare the longer instructions on the old site:
> https://old.grass.osgeo.org/download/software/ms-windows/#osgeo4w
> which offer insights on _Express Desktop Install_ and _Advanced Install_ ...
> 
> How about a (new) Wiki page with more details, then to be linked?

I suggest to add some more hints and information to the download page about advanced mode and useful python packages to the download page.

**Comment by hellik** [comment]
PR opened for the OSGeo4W download section

**Comment by hellik** [comment]
wiki updated

**Comment by neteler** [comment]
To me, honestly, it still looks a bit unstructured. Also the Wiki page link is hard to spot. and the command line maybe move down?
Or, introduce some color boxes?

Current screenshot:

![image](https://user-images.githubusercontent.com/1295172/102411963-1f51f600-3ff3-11eb-9a98-a71c687d2ad3.png)

**Comment by hellik** [comment]
Maybe asking our users what is still missing would help to improve this kind of information.

**Comment by neteler** [comment]
Here an idea (quickly drawn in LibreOffice):

![image](https://user-images.githubusercontent.com/1295172/102513079-0e54c380-408b-11eb-8edd-4ecaf5e3e3cf.png)
