### ISSUE TITLE
Broken links for logos on Download page

### ISSUE THREAD

**Issue by baharmon** [OSGeo/grass-website#237]
The links for the GRASS logos for Windows, Mac, and Linux on the Downloads page are broken. The titles for the download pages are also wrong. See for example: https://grass.osgeo.org//images/logos/grass-GRASS%20GIS%20for%20Linux.jpg
This is due to the titles on the download pages for each OS being set to `GRASS GIS for [OS]` rather than just `[OS]`.
This results in page titles like `GRASS GIS for GRASS GIS for Linux` and image links like: 
`<div class="col-4 text-center"><img src="{{.Site.BaseURL}}/images/logos/grass-{{.Title}}.jpg"></div>`

**Comment by baharmon** [comment]
I will submit a pull request with a proposed fix soon.

**Comment by neteler** [comment]
Oh, I see. I was introducing this in #235 and didn't expect that the title is used in that way.
My rationale was that the page titles are unhelpful as such (what does "Windows" mean?).

@nbozon any idea how to overcome this conflict besides reverting the previous title changes?

**Comment by lucadelu** [comment]
> Oh, I see. I was introducing this in #235 and didn't expect that the title is used in that way.
> My rationale was that the page titles are unhelpful as such (what does "Windows" mean?).
> 
> @nbozon or @lucadelu any idea how to overcome this conflict besides reverting the previous title changes?

I don't know, but for now I would revert the title name that you changed
