### ISSUE TITLE
Improve visibility of mailing lists and add "Forum" section

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#245]
At time the visibility of our mailing list is rather limited, at the related [Community](https://grass.osgeo.org/about/community/) page resides under "About" which isn't intuitive when searching for "**Support**" (which we don't have - unlike on https://old.grass.osgeo.org/support/).

I don't have any obvious idea yet how to address that (different menu entry?) - suggestions are welcome.

While at it, we may also add a section "**Forum**", with
- https://gis.stackexchange.com/questions/tagged/grass
- Nabble mailing list mirror: http://osgeo-org.1560.x6.nabble.com/GRASS-f3884508.html (hint: the recent nabble spam has be flagged [here](https://lists.osgeo.org/pipermail/sac/2021-January/013009.html))
- MARC mailing list mirror: https://marc.info/?w=4&r=1&s=grass&q=l
- anything else?

And also create a "**Commercial support**" subpage, see existing issue #34

**Comment by ecodiv** [comment]
Why not a separate menu for communiteit or alternatively support? It is such an essential part, a key selling point.

**Comment by neteler** [comment]
I much like the idea to promote "Community" to the top level menu!

**Comment by petrasovaa** [comment]
This seems to have been addressed by https://github.com/OSGeo/grass-website/pull/369.
If there is anything left, open a separate issue.
