### ISSUE TITLE
RSS feed broken: index.xml - 404

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#247]
For (to me) unknown reasons the feed is no longer there, likely already for a while:

https://grass.osgeo.org/index.xml - 404

It was originally introduced in 2ad7366bdbed7ac8aaff7b1ba98bdc7d948f4e05 and the URL then updated after the DNS switch to "production" in e6dfabd6a5deaf7678f28ed1115958b5e1eb7c98.

The absence of `index.xml` leads to a non-indexing by https://planet.osgeo.org/ and elsewhere, reducing our news visibility.

**Comment by veroandreo** [comment]
I was inspecting the docs here: https://gohugo.io/templates/rss/ and the [default template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/_default/rss.xml) shipped with hugo, and I didn't find much differences... no idea

**Comment by lucadelu** [comment]
I also have no idea, sorry

**Comment by neteler** [comment]
I found it. The reason is that #242 (which I applied on the server for testing) damages the RSS feed.

I have now reverted the manual patch on the server and RSS is back.
