### ISSUE TITLE
Gallery of screenshots

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#25]
Would it be possible to add gallery support? We have lots of screenshots available, would be nice to show them.

Thanks.

**Comment by ninsbl** [comment]
See: https://www.liwen.id.au/heg/#gallery-usage / https://github.com/liwenyip/hugo-easy-gallery/

**Comment by veroandreo** [comment]
There's also the hugo-academic implementation: https://github.com/gcushen/hugo-academic/blob/master/layouts/shortcodes/gallery.html

**Comment by lucadelu** [comment]
see also #50

**Comment by lucadelu** [comment]
Other themes here https://themes.gohugo.io/tags/gallery/ look for AutoPhugo and Photo Grid, this seems better then others and more updated

**Comment by nbozon** [comment]
Implemented in  #133 
Please review @neteler @lucadelu  @veroandreo @ninsbl

**Comment by neteler** [comment]
Anything left open here?

**Comment by veroandreo** [comment]
The fixes suggested in the already closed PR #133, I'll open a new issue for that so we do not loose it
