### ISSUE TITLE
Rename Donations --> Sponsoring

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#250]
Let me suggest to rename (with redirect) and update this page:
https://github.com/OSGeo/grass-website/blob/master/content/contribute/donations.md

in terms of the wording: Donations --> Sponsorship

_Rationale_: Donations implies a legal framework (at least in some countries) and may keep business/industrial sponsoring out of the options.

I got this idea when reading

"[Projects] project sponsorship": https://lists.osgeo.org/pipermail/projects/2021-February/000286.html

Or is this first a question for the [PSC](https://trac.osgeo.org/grass/wiki/PSC/Agenda)?

**Comment by mlennert** [comment]
On 2/02/21 13:43, Markus Neteler wrote:
> Let me suggest to rename (with redirect) and update this page:
> https://github.com/OSGeo/grass-website/blob/master/content/contribute/donations.md 
> <https://github.com/OSGeo/grass-website/blob/master/content/contribute/donations.md>
> 
> in terms of the wording: Donations --> Sponsorship

+1

> 
> /Rationale/: Donations implies a legal framework (at least in some 
> countries) and may keep business/industrial sponsoring out of the options.
> 
> I got this idea when reading
> 
> "[Projects] project sponsorship": 
> https://lists.osgeo.org/pipermail/projects/2021-February/000286.html 
> <https://lists.osgeo.org/pipermail/projects/2021-February/000286.html>
> 
> Or is this first a question for the PSC 
> <https://trac.osgeo.org/grass/wiki/PSC/Agenda>?


Don't think so, but if you feel it is, you can put it onto the agenda 
for this week's meeting.

Moritz

**Comment by neteler** [comment]
Maybe PSC is not needed (and I'll add a redirect to the Apache server rules). However,

- https://grass.osgeo.org/contribute/sponsoring , or
- https://grass.osgeo.org/contribute/sponsorship
- something else

?

**Comment by veroandreo** [comment]
Sorry for the delay. I was just checking QGIS site and they have a nice donations page (https://qgis.org/en/site/getinvolved/donations.html) but of course they are huge and then they also have a sustaining membership program for bigger money...

**Comment by neteler** [comment]
(for QGIS, the concepts of sponsors has been replaced by sustaining membership, as per [here](https://lists.osgeo.org/pipermail/projects/2021-February/000287.html))

**Comment by neteler** [comment]
Page renamed to https://grass.osgeo.org/contribute/sponsoring/
and Apache redirection in place

**Comment by neteler** [comment]
Related OSGeo ticket updated accordingly: https://git.osgeo.org/gitea/osgeo/todo/issues/106
