### ISSUE TITLE
Problem with site URL

### ISSUE THREAD

**Issue by nbozon** [OSGeo/grass-website#26]
We have a major issue with the website Site.BaseURL param
    
     baseURL = "https://staging.grass.osgeo.org/"

The index.html page is **https://staging.grass.osgeo.org**  whereas all other pages are HTTP instead of HTTPS, such as **http://staging.grass.osgeo.org/learn/manuals/**  

We need to fix this ASAP, as it is responsible for CORS errors on multiple subpages, and webfonts (or other local ressources) are thus throwing errors

**Comment by neteler** [comment]
See also #20

**Comment by nbozon** [comment]
yes, but i am still wondering why our index page is correctly certified as https, but all other pages aren't .. this actually breaks the local fonts (and icons)

**Comment by neteler** [comment]
I checked, it seems the https certificate is only for the landing page, and not configured in the Apache server.
I try to contact Regina (OSGeo-SAC) for that.

**Comment by neteler** [comment]
New ticket at https://trac.osgeo.org/osgeo/ticket/2427

**Comment by neteler** [comment]
@nbozon, could you pls check the new answer in the trac ticket above? (The host machine is a nginx server.)

**Comment by neteler** [comment]
See also new ticket https://trac.osgeo.org/osgeo/ticket/2428

**Comment by neteler** [comment]
> yes, but i am still wondering why our index page is correctly certified as https, but all other pages aren't .. this actually breaks the local fonts (and icons)

Regina (OSGeo-SAC) kindly just fixed it.
