### ISSUE TITLE
Links to 7.8 Manual Get 404 Error

### ISSUE THREAD

**Issue by dkav** [OSGeo/grass-website#263]
The links for the [7.8 manual](https://grass.osgeo.org/grass78/manuals/index.html) in the [manuals page](https://grass.osgeo.org/learn/manuals/) and elsewhere (e.g. see link in note in [7.6 manual](https://grass.osgeo.org/grass76/manuals/index.html)) get a 404 error.

**Comment by veroandreo** [comment]
Thanks, it was also reported in grass-dev mailing list: https://lists.osgeo.org/pipermail/grass-dev/2021-September/095400.html. 

The compilation logs seem fine though: https://grass.osgeo.org/grass78/binary/linux/snapshot/error.log

**Comment by petrasovaa** [comment]
Seems to work now!

**Comment by landam** [comment]
Generation of manual pages including addons fix by https://github.com/OSGeo/grass-addons/pull/613
