### ISSUE TITLE
Add links to sample data

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-website#27]
Maybe under "learn"?
See: https://grass.osgeo.org/download/sample-data/

**Comment by lucadelu** [comment]
I like more under Download

**Comment by veroandreo** [comment]
It could go under *Download* as it is now in the "old" website (Software and Sample Data), but if that's the final choice we should add a nice big link under Learn, too. It makes sense to me that after filling the content of *Learn* with links to tutorials, courses and such, we put a link to Sample data as well

**Comment by nbozon** [comment]
+1 to add it under Download, as in the current website

> In general, I'm in favor of shrinking and re-structuring, keeping only relevant content, and not just copy-pasting

Strong +1 here, this is the main point of rewriting the website, to make it more clear by keeping relevant content only -

**Comment by nbozon** [comment]
Done, see:
https://staging.grass.osgeo.org/download/data/ (content still to be added)
Link to this page is now also available from the top menu and from the Download index page (https://staging.grass.osgeo.org/download/)

**Comment by ninsbl** [comment]
Closing this. Feel free to open a new issue with further improvements.
