### ISSUE TITLE
Update download data page

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#278]
Once GRASS 8 is out, we need to update https://grass.osgeo.org/download/data/ since startup will be gone

![image](https://user-images.githubusercontent.com/20075188/149623294-21b6ce06-4070-4c13-a866-7ddf9862314b.png)

**Comment by neteler** [comment]
Seems to be done... in #282.

**Comment by veroandreo** [comment]
> Seems to be done... in #282.

Indeed! I forgot to close this one, thanks!
