### ISSUE TITLE
Download of Windows RC1 broken render

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass-website#280]
The download link of Windows RC1 is broken, since the markdown formatting is inside the HTML div with the #274 changes.

I tried some fixes. 
### Solution 1
Either convert the list in plain html, having a green link in the blue info panel, like:
```html

#### <a name="GRASS-GIS-devel"></a> GRASS GIS 8.0

<div class="alert rounded-0 alert-info">
<i class="fa fa-info-circle"></i> Active <u>development</u> and <u>upcoming new stable</u> <b>GRASS GIS</b> version. <br>

<li><a class="int" href="https://grass.osgeo.org/grass80/binary/mswindows/native/WinGRASS-8.0.0RC1-1-Setup.exe"><i class="fa fa-download"></i> Download RC1</a></li>

</div>

*  Final release coming soon!

<hr>
```

![image](https://user-images.githubusercontent.com/27212526/150647073-7c134722-1f1e-4887-82d5-8eb275ded796.png)

### Solution 2
Or move the link out of the div, and have the link outside the info panel, towards the text:
```html
#### <a name="GRASS-GIS-devel"></a> GRASS GIS 8.0

<div class="alert rounded-0 alert-info">
<i class="fa fa-info-circle"></i> Active <u>development</u> and <u>upcoming new stable</u> <b>GRASS GIS</b> version.</div>

*  [<i class="fa fa-download"></i> Download RC1](https://grass.osgeo.org/grass80/binary/mswindows/native/WinGRASS-8.0.0RC1-1-Setup.exe)
*  Final release coming soon!

<hr>
```

![image](https://user-images.githubusercontent.com/27212526/150647081-7e31be37-4902-465c-9096-9a3d142c4077.png)

I'll make a pull request with the solution you think is best.
It was my first time using Hugo and I'm impressed with its speed and automatic rendering and reloading when any changes are made. Quite useful!

**Comment by nilason** [comment]
I’d say solution no 2, to keep consistency within the file.

**Comment by landam** [comment]
+1 for solution 2 (same layout as for other GRASS version). 

BTW, there is already RC2 out (https://grass.osgeo.org/grass80/binary/mswindows/native/WinGRASS-8.0.0RC2-1-Setup.exe).

@echoix Are you planning to create a pull request? Thanks.

**Comment by echoix** [comment]
I can this morning, or there's the code already. Maybe just use the RC2
