### ISSUE TITLE
Repo settings: Change settings to Squash

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass-website#286]
I think you want to change _Settings > Merge button_ to _Squash and merge_ only.

...or add me as an owner and I'll do it.

**Comment by neteler** [comment]
I have now added the `grass-admins` team which includes you.
Now you should be able to make the needed setting fixes.

**Comment by veroandreo** [comment]
ops, I overlooked that yesterday, I'm used to grass-core and addons repos it seems. Apologies :)

**Comment by neteler** [comment]
Now set to:

![image](https://user-images.githubusercontent.com/1295172/194718137-ca133757-e2a4-4070-b26b-d5c9e7f6dc5e.png)

**Comment by wenzeslaus** [comment]
Thanks!
