### ISSUE TITLE
Should AddOns become more visible?

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-website#29]
Addons seem to be very little visible. Maybe worth a subpage under Development, and a paragraph under https://staging.grass.osgeo.org/learn/overview/?

**Comment by lucadelu** [comment]
Under Development a addons session is already there #11 

We can add in overview  under "Main feature" section

**Comment by veroandreo** [comment]
+1 to add *Add-ons* in the Overview too

**Comment by veroandreo** [comment]
I'm thinking that we can also add the Add-ons repo link in the *Download* page. What do you think?

**Comment by lucadelu** [comment]
I'm going to add in _Download_ page and "Main features" section

**Comment by veroandreo** [comment]
Thanks Lu! I did some proof-reading :)

**Comment by veroandreo** [comment]
> Under Development a addons session is already there #11
> 
> We can add in overview under "Main feature" section

@lucadelu What do you think of these paragraphs for  the overview?

### Add-ons: GRASS GIS extensions

GRASS GIS capabilities are significantly increased by an impressive list of extensions or **add-ons**. These modules are contributed by users or developers but are not yet part of the standard distribution. They can be easily installed through the extension manager in the GUI or with the [g.extension](https://grass.osgeo.org/grass78/manuals/g.extension.html) module in the command line. There are currently more than **350 extensions** in the official [GRASS Add-ons repo](thub.com/OSGeo/grass-addons/tree/master/grass7) and many others in the wild to perform the most varied type of tasks. 

Have a look at the full list of [add-ons manual pages](https://grass.osgeo.org/grass7/manuals/addons/) to get an idea. If you don't find what you need, maybe you can [develop](/content/contribute/development) your own add-on then.

**Comment by lucadelu** [comment]
Done
