### ISSUE TITLE
Add history to "About"

### ISSUE THREAD

**Issue by marisn** [OSGeo/grass-website#30]
GRASS GIS has a long history and that should not be forgotten! How about adding a history page to "About"? Page content can be lifted from the current [History page](https://grass.osgeo.org/home/history/) ( + Releases; Documents and 
L. Van Warren's historical note).

Discuss!

**Comment by ninsbl** [comment]
See #12

**Comment by veroandreo** [comment]
In my opinion, we need to restructure and shrink the *history* page to include it in the new website. For example, all the list of releases can just go to the wiki, the roadmap graphic can be updated, all the SVN part can also go to the wiki, as well most of the documents

**Comment by neteler** [comment]
The https://staging.grass.osgeo.org/about/history/ is now there.

Further cleanup is needed but that's probably to be handled in separate ticket(s)....

**Comment by lucadelu** [comment]
I suggest to move to wiki page `Hosting agencies for the GRASS conferences` section and maybe also the `Trivia` section, what do you think?
The other part I like it, maybe we should add a picture for each period...

**Comment by veroandreo** [comment]
> I suggest to move to wiki page `Hosting agencies for the GRASS conferences` section and maybe also the `Trivia` section, what do you think?
> The other part I like it, maybe we should add a picture for each period...

Yes, agreed. I'll work on this during the weekend. @neteler if you then can find some old pics to illustrate, I'd appreciate :)

**Comment by neteler** [comment]
> Yes, agreed. I'll work on this during the weekend. @neteler if you then can find some old pics to illustrate, I'd appreciate :)

Happy to contribute, pls let me know what you need beyond the recently uploaded gallery material (PR #50).

**Comment by veroandreo** [comment]
This was added by #83. Closing.
