### ISSUE TITLE
Add content to the Download section

### ISSUE THREAD

**Issue by nbozon** [OSGeo/grass-website#31]
Replace Lorem Ipsum and empty sections with appropriate content and links

**Comment by nbozon** [comment]
Done for Linux, see:
https://staging.grass.osgeo.org/download/linux/
Please check links, and add any missing information

**Comment by nbozon** [comment]
Done for Windows, see:
https://staging.grass.osgeo.org/download/windows/
Please check links, and add any missing information

**Comment by lucadelu** [comment]
Please see #37

**Comment by nbozon** [comment]
Done for Mac (partly), see:
https://staging.grass.osgeo.org/download/mac/
Please check links, and add missing information @lucadelu @veroandreo @neteler

**Comment by nbozon** [comment]
Done for Docker, see:
https://staging.grass.osgeo.org/download/docker/
Please check links, and add any missing information

**Comment by nbozon** [comment]
Done for Sample data (partly), see:
https://staging.grass.osgeo.org/download/data/
Please sort and add missing content @lucadelu @veroandreo

**Comment by mlennert** [comment]
See specific issues for different OS
