### ISSUE TITLE
[Bug] gis.stackexchange.com/questions/tagged/grass missing from Community page

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#313]
The GRASS GIS Community page (https://grass.osgeo.org/about/community/) should also list

https://gis.stackexchange.com/questions/tagged/grass

(requires an icon to be prepared).

**Comment by veroandreo** [comment]
Where would you add it: within mailing list, social media or as a separate section? 

There's this icon in font awesome: https://fontawesome.com/icons/stack-exchange?s=brands. Would that do?

**Comment by neteler** [comment]
I have now added it as a separate "Q&A" section in PR #317:

![image](https://user-images.githubusercontent.com/1295172/183412014-a2ef18c7-250f-48c1-bfbd-11b5d65ecd60.png)
