### ISSUE TITLE
Sync man page versions

### ISSUE THREAD

**Issue by marisn** [OSGeo/grass-website#315]
In GRASS website:
* download section lists latest version as being 8.2
* manual section lists latest version as being 8.0
* manual itself has a version of 8.0.3dev

Apparently release procedure needs to be updated to correctly update man page links too.

**Comment by neteler** [comment]
I'd suggest to use variables here (if possible), interpreted by hugo, defined in https://github.com/OSGeo/grass-website/blob/master/config.toml or the like.

**Comment by veroandreo** [comment]
@nobeeakon do you have an idea on how this might be implemented?

**Comment by neteler** [comment]
Great work in #318, @nobeeakon !
