### ISSUE TITLE
show donate dialog when downloading

### ISSUE THREAD

**Issue by nobeeakon** [OSGeo/grass-website#316]
Show a dialog that motivates the user to donate to the project when downloading the software (maybe even when dowloading docker images and sample data). Something like what they do on QGIS, the dialog pops up when clicking download, shows some text and a CLOSE and DONATE buttons. DONATE could link directly to https://opencollective.com/grass 
![imagen](https://user-images.githubusercontent.com/12853324/183106875-ca8fc4b7-f572-4223-a559-e8aa1546f978.png)

**Comment by veroandreo** [comment]
I like this idea :)

**Comment by nobeeakon** [comment]
nice @veroandreo  :) , I can do it, just think it would be better if you guys choose the image and the wording for the message, maybe something brief? (think that the QGIS one is quite large)

**Comment by veroandreo** [comment]
A very simple text snippet could go on these lines: 

## Thanks for choosing GRASS GIS!

Your free and open source copy of GRASS GIS (version variable here?) will download now. If you or your company enjoy the software, please consider making a [donation](https://opencollective.com/osgeo/projects/grass) to support the project. May the FOSS be with you!

*GRASS Team*

(and the buttons as in the QGIS dialog)

Some pic options (we should make a new one :)):
- https://grass.osgeo.org/images/news/grassgis2020.jpg
- https://grass.osgeo.org/images/news/grass_sprint2018_bonn_fotowall_medium.jpg
- https://github.com/veroandreo/grass-gis-talks/blob/main/img/bonn_osgeo_code_sprint_2018.jpg
- https://github.com/veroandreo/grass-gis-talks/blob/main/img/grass_team.jpg (2012)
