### ISSUE TITLE
visitibility to gitter chat

### ISSUE THREAD

**Issue by nobeeakon** [OSGeo/grass-website#329]
As Gitter chat room  has been recently opened, think it would be useful to make it visible to users, this will help to get the community started otherwise people may not even know about it and it will be kind of difficult that that community grows.

It could be something like: 

1. having a banner at the top of the page. Not sure if this has been done in the past, and if so, how  has it been done. Maybe below the menu bar.  Think it would be useful to keep the banner for some time (2-3 months) so that people notice it. It should have a message inviting people to join gitter.

2. adding an icon at the bottom , within the icons section, maybe after the github icon

**Comment by nobeeakon** [comment]
what about something like 
![imagen](https://user-images.githubusercontent.com/12853324/187107656-4a229745-2e24-4d76-8433-a974164e329b.png)

message and colors are just a proposal. Think it would be useful to show it in the home page but in other places of the site as well (contribute, dev, learn, download, etc)...

**Comment by neteler** [comment]
I like this "banner" idea! :+1:
