### ISSUE TITLE
Create a commercial support subpage

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#34]
Content could be a subset of the info here https://grass.osgeo.org/support/commercial-support/ with companies/institutions logos instead of just a list of links

**Comment by neteler** [comment]
And/or could that be somehow connected to https://www.osgeo.org/service-providers/ ?

**Comment by wenzeslaus** [comment]
The OSGeo page does not have filtering by specific software (perhaps it could), so I think we should have our own page. Perhaps there is also a value in having it on our site as opposed to redirecting people to another web site.

On the other hand, linking the OSGeo page as something like "more OSGeo service/support providers [at OSGeo website]" makes a lot of sense to me.

**Comment by lucadelu** [comment]
Make sense to me too

**Comment by wenzeslaus** [comment]
Done in #369
