### ISSUE TITLE
https://grass.osgeo.org/

### ISSUE THREAD

**Issue by withgaurav** [OSGeo/grass-website#347]
I want to make this website UI more beautiful.

**Comment by petrasovaa** [comment]
Thanks for your interest! One issue you could look at is updating fontawesome:
https://github.com/OSGeo/grass-website/pull/345#issuecomment-1363345403

Others may have more ideas what to start with...

**Comment by veroandreo** [comment]
Hi @withgaurav, thanks for your interest in our website. Please tell us more about your ideas or directly open PR(s) with suggestions and screenshots so we can have a look :)

**Comment by withgaurav** [comment]
Thank you for your reply @petrasovaa @veroandreo where we can contact each other

**Comment by veroandreo** [comment]
> Thank you for your reply @petrasovaa @veroandreo where we can contact each other

Here :wink: 

As @petrasovaa mentioned, you can start by trying to solve https://github.com/OSGeo/grass-website/pull/345#issuecomment-1363345403, for example. Also, you can tell us here about your ideas to beautify GRASS website or directly propose them via PR to this repo. The basic instructions to contribute are in the [README](https://github.com/OSGeo/grass-website#readme)

**Comment by withgaurav** [comment]
I am facing problem in running apt-get update command can you please help!! @petrasovaa @veroandreo

**Comment by nobeeakon** [comment]
Hi @withgaurav , also you could try asking in https://gitter.im/grassgis/community , could be (up to a certain point) quicker if you are facing issues

**Comment by echoix** [comment]
On what system are you? Are you on a Windows system or on a Linux, Ubuntu/Debian specifically?

**Comment by withgaurav** [comment]
I am on a window system @echoix

**Comment by echoix** [comment]
The instructions are for Ubuntu/Debian users. If you download Hugo from the website or GitHub releases for the Windows version, a similar command would probably work fine (maybe using `hugo.exe server` instead of `hugo server`)

**Comment by withgaurav** [comment]
@echoix okay sure I will do

**Comment by withgaurav** [comment]
@echoix If you don't mind Can I get your email address?

**Comment by echoix** [comment]
I was working on setup to use directly on Gitpod that had the configuration done (in the week and yesterday), but wasn't quite ready yet. I wanted to have GitHub codespaces made too, but didn't get a consistent experience.

**Comment by echoix** [comment]
> @echoix If you don't mind Can I get your email address?

Find me on LinkedIn if you need, I could write it out there instead of publicly. I still have like two hours free.

**Comment by echoix** [comment]
That was one my tries on the branch https://github.com/echoix/grass-website/tree/gitpod-button-2, the link https://gitpod.io/#https://github.com/echoix/grass-website/tree/gitpod-button-2 can be shown like this: 
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#https://github.com/echoix/grass-website/tree/gitpod-button-2)

But it's on my repo instead of the main one. Do you know how to create a branch on your fork to contribute?

**Comment by withgaurav** [comment]
@echoix 

> > @echoix If you don't mind Can I get your email address?
> 
> Find me on LinkedIn if you need, I could write it out there instead of publicly. I still have like two hours free.

Yeah Sure, I got you there

**Comment by withgaurav** [comment]
> That was one my tries on the branch https://github.com/echoix/grass-website/tree/gitpod-button-2, the link https://gitpod.io/#https://github.com/echoix/grass-website/tree/gitpod-button-2 can be shown like this: [![Open in Gitpod](https://camo.githubusercontent.com/76e60919474807718793857d8eb615e7a50b18b04050577e5a35c19421f260a3/68747470733a2f2f676974706f642e696f2f627574746f6e2f6f70656e2d696e2d676974706f642e737667)](https://gitpod.io/#https://github.com/echoix/grass-website/tree/gitpod-button-2)
> 
> But it's on my repo instead of the main one. Do you know how to create a branch on your fork to contribute?

Yes I know

**Comment by withgaurav** [comment]
@neteler class="mt-2 mb-4" This class is not defined in CSS. Can I define a new class?

**Comment by withgaurav** [comment]
When I am opening this link 
![image](https://user-images.githubusercontent.com/76643106/215571023-c7002628-ca4b-47ad-915f-8595c5514c6b.png)

so it is showing this type of error

![image](https://user-images.githubusercontent.com/76643106/215570935-7b90614e-0f03-495b-8cb8-de3fb63cc252.png)


@petrasovaa @neteler @echoix

**Comment by neteler** [comment]
> @neteler class="mt-2 mb-4" This class is not defined in CSS. Can I define a new class?

It is defined:
https://github.com/OSGeo/grass-website/blob/84ab8fc9bd294a8a160e1993c4a3a69b3733ecf8/themes/grass/assets/css/style.css#L488

**Comment by withgaurav** [comment]
@veroandreo I have tried to make some of the changes on website #355. Please review it and let me know more about it.

**Comment by veroandreo** [comment]
I'm closing this one as #355 and #356 are also closed. @withgaurav you can then open a new one.
