### ISSUE TITLE
Add Community Sprint pics to Donation subpage

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#35]
[Donations page](https://staging.grass.osgeo.org/contribute/donations/) would look better with some pics :)

Since Community sprints are mentioned a couple of times, it would be nice to add some pics there. If you have some, please share

**Comment by neteler** [comment]
This one for example:

https://grasswiki.osgeo.org/wiki/File:Grass_sprint2018_bonn_fotowall.jpg
