### ISSUE TITLE
How to use the grass version number variables in HTML?

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#351]
(this related to "fix/grass version numbers #318")

While I know how to use the variables in .md files, how to use it in .html?

Specifically, I want to add a line with the current version number to `themes/grass/layouts/404.html` since I see from our Matomo statistics that ppl try to find very old versions (they go to old news for whatever reason, then fail to find very old binaries) and need a hint about the current version on the "404" page:

```
            <br><br>
            Current version: GRASS GIS {{< grassVersion version="current" >}}
```

Now, `hugo server` dislikes this addition (as it is likely in markdown-only style).

Any pointer on usage of the variables in HTML files would be welcome.

**Comment by veroandreo** [comment]
This worked: `GRASS version:  GRASS GIS {{ .Site.Data.grass.current_version }}`. I found it here: https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/shortcodes/grassVersion.html and the local build seems ok:

![image](https://user-images.githubusercontent.com/20075188/216791327-30ff7447-6fe8-4d26-97f1-aadffc68e6e6.png)

Was that what you wanted to get?

**Comment by neteler** [comment]
Cool, this helped. PR created: #353
