### ISSUE TITLE
Add docker images to Download page

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#36]
[Download page](https://staging.grass.osgeo.org/download/) is missing a *Docker* section and subpage where to add (a subset of) the contents currently in https://grass.osgeo.org/download/software/docker-images/

**Comment by nbozon** [comment]
Added in a new /download/docker.md file, with content taken from current website. Added a logo images (as for linux, windows and mac)

Please see:
https://staging.grass.osgeo.org/download/docker/
Could you please review and check @neteler  ?
