### ISSUE TITLE
Twitter timeline no longer fed into website

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#363]
It seems that the Twitter feed widget is no longer working...

![image](https://user-images.githubusercontent.com/20075188/233797227-930c144a-f3dd-460b-ab0a-99146142933a.png)

Apparently, there were some changes: https://twittercommunity.com/t/embedded-timelines-update-parameters-support/177112 and https://developer.twitter.com/en/docs/twitter-for-websites/timelines/overview

So, I followed the instructions to create a new one and embed the link within the news page. I can see it rendered here:
https://publish.twitter.com/?buttonType=MentionButton&query=https%3A%2F%2Ftwitter.com%2FGRASSGIS&widget=Timeline, but when I compile the website locally with the new link, the feed does not appear. So, I'm unsure about creating a PR.

any ideas?

**Comment by nobeeakon** [comment]
fixed in https://github.com/OSGeo/grass-website/pull/365
