### ISSUE TITLE
Fix content in Download/mac

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#37]
Content in [Mac](https://staging.grass.osgeo.org/download/mac/) subpage should ideally be similar to content in linux and windows subpages

**Comment by nbozon** [comment]
The same design and headlines + alerts styles are now applied, see:
https://staging.grass.osgeo.org/download/mac/

Versions content and links were left blank for now, as i am not sure about what' to take from the current site AND from the grassformac website ... @neteler @veroandreo @lucadelu could you please check and edit the page accordingly ?

**Comment by lucadelu** [comment]
I have no idea about Mac situation; @petrasovaa @wenzeslaus do you any updates about this?

**Comment by neteler** [comment]
it now looks much better: https://staging.grass.osgeo.org/download/mac/
Can this ticket be closed?

**Comment by veroandreo** [comment]
yes, just see my comment here https://github.com/OSGeo/grass-website/pull/139#issuecomment-624077619

**Comment by veroandreo** [comment]
> yes, just see my comment here [#139 (comment)](https://github.com/OSGeo/grass-website/pull/139#issuecomment-624077619)

I just fixed this in https://github.com/OSGeo/grass-website/commit/24ac0c38b75cbf7846ac0deca0ef4a34c385eb29, closing
