### ISSUE TITLE
What's the difference between Download and Install buttons in download page?

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#38]
Currently, both Download and Install buttons here https://staging.grass.osgeo.org/download/# point to the same content. Shall we better keep one or the other? I don't understand what would be the expected content in the install button. I'd rather keep only the download one. 

Opinions?

**Comment by nbozon** [comment]
The initial idea was to  propose two links, one to the Download page, the other to the related installation wiki page.. But i agree this is not needed here.

**Comment by nbozon** [comment]
Fixed, please see:
https://staging.grass.osgeo.org/download/
The uneeded "Install" button was removed and one simple sentence is added below instead (taken from each file frontmatter description parameter).

**Comment by veroandreo** [comment]
Thanks!
