### ISSUE TITLE
Twitter feed not working

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#380]
The twitter feed is no longer working. Check: https://grass.osgeo.org/news/

![image](https://github.com/OSGeo/grass-website/assets/20075188/0dd687cf-881e-4799-82ee-7ef4b23fc144)

**Comment by neteler** [comment]
Should in theory happen in 
https://github.com/OSGeo/grass-website/blob/master/themes/grass/layouts/partials/twitter.html

which points to
https://platform.twitter.com/widgets.js

Documented at
https://developer.twitter.com/en/docs/twitter-for-websites/javascript-api/guides/set-up-twitter-for-websites

(not really my field :) )

**Comment by neteler** [comment]
I have read somewhere that the X feed visibility now depends on paying for it (at least apparently valid for Wordpress plugins). Doesn't seem to have much future.

Alternative PR forthcoming.

**Comment by wenzeslaus** [comment]
Maybe even a link to social media is enough.

**Comment by neteler** [comment]
We have that in the footer.

I have created a Mastodon feed PR.

**Comment by veroandreo** [comment]
Seems to be up again... did you change anything @neteler ? Or perhaps it was down for some reason and they (X) fixed it?

![image](https://github.com/OSGeo/grass-website/assets/20075188/5b3d8868-825f-4d56-9add-fac9921fa021)

**Comment by neteler** [comment]
> did you change anything @neteler ?

I did't touch anything - see git history :-)

**Comment by neteler** [comment]
> Seems to be up again..

Here, for me (Firefox, if that matters) is doesn't work. Still outage.

**Comment by neteler** [comment]
Indeed, it works being authenticated to X. If not, this "Nothing to see here" shows up.
