### ISSUE TITLE
Typo in image tag names

### ISSUE THREAD

**Issue by mxkpp** [OSGeo/grass-website#386]
"releasebranch" mispelled as "relesebranch"

https://github.com/OSGeo/grass-website/blob/8a027a9f0db4d9348b4f48c61a671e7c743407ed/content/download/docker.en.md?plain=1#L24

**Comment by neteler** [comment]
Thanks for catching this! PR is on the way.

**Comment by neteler** [comment]
Fixed at
https://grass.osgeo.org/download/docker/
