### ISSUE TITLE
update footer

### ISSUE THREAD

**Issue by AnishHazra** [OSGeo/grass-website#392]
assigned me footer work i can update it

**Comment by neteler** [comment]
Feel free to suggest changes. See also
https://github.com/OSGeo/grass-website/blob/master/README.md

**Comment by veroandreo** [comment]
Indeed, we'd need to update the fontawesome version so we are able to change the former twitter bird to X icon

**Comment by neteler** [comment]
Is anything still open here?

**Comment by veroandreo** [comment]
> Is anything still open here?

seems not, closing
