### ISSUE TITLE
[Bug] New "Support" menu is broken

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#397]
Not sure what happened but the "Support" menu is entirely broken:

![image](https://github.com/OSGeo/grass-website/assets/1295172/f6430ee3-10e6-45e3-8e28-ac192ac2b305)

**404**:

- https://grass.osgeo.org/about/community/
- https://grass.osgeo.org/about/community/commercial
- https://grass.osgeo.org/about/community/community

_Originally posted by @neteler in https://github.com/OSGeo/grass-website/issues/369#issuecomment-1793423649_

**Comment by veroandreo** [comment]
I cannot reproduce this locally, the site builds just fine and I get redirected to the right pages, no 404... I wonder if the version difference starts to be a problem...

**Comment by neteler** [comment]
> I wonder if the version difference starts to be a problem...

You refer to hugo, I suppose? Which version do you use locally?

**Comment by veroandreo** [comment]
> > I wonder if the version difference starts to be a problem...
> 
> You refer to hugo, I suppose? Which version do you use locally?

Yes, hugo and go as well. I use hugo 0.98 (which is oldish anyway) and go 1.20

**Comment by petrasovaa** [comment]
I have newer one 0.110 and locally it looks just fine.

**Comment by neteler** [comment]
On the server we have:

```
neteler@grasslxd:~$ dpkg -l | grep hugo
ii  hugo                                   0.80.0-6+b5
```

So, linking to #312 and #394

**Comment by nilason** [comment]
I'm not that familiar with Hugo and how it works, but couldn't there be some cache file or other remaining file. I understand that one page has moved below another parent page (about/community -> support/community).

There is some strange redirection or url:
https://grass.osgeo.org/support/community is redirected to https://grass.osgeo.org/about/community/community

**Comment by neteler** [comment]
Bingo, @nilason 

Indeed, `/etc/apache2/sites-enabled/000-default.conf` contained

```
    Redirect 301 /support/ https://grass.osgeo.org/about/community/
    Redirect 301 /support/commercial-support https://grass.osgeo.org/contribute/sponsoring/
    Redirect 301 /support/mailing-lists/ https://grass.osgeo.org/about/community/
```

Removed now, it was in place to catch outdated references from the previous CMSMS instance which we replaced with hugo.

Lines removed and server restarted.

**Comment by nilason** [comment]
Great!
