### ISSUE TITLE
News: detailed news do not yet show their date

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#40]
While the news overview nicely shows the respective date:

* https://staging.grass.osgeo.org/ --> scroll

... it is missing from the news itself, example:

https://staging.grass.osgeo.org/news/svn-migration-has-started/

Wish: pls also show the date within the news page itself. Likely to be updated in the style.

**Comment by lucadelu** [comment]
> While the news overview nicely shows the respective date:
> 
>     * https://staging.grass.osgeo.org/ --> scroll
> 
> 
> ... it is missing from the news itself, example:
> 
> https://staging.grass.osgeo.org/news/svn-migration-has-started/
> 
> Wish: pls also show the date within the news page itself. Likely to be updated in the style.

Where do you like the date? under the title or at the end of the page?
And which format do you like? You can see some formats [here](https://gohugo.io/functions/format/)

**Comment by neteler** [comment]
Since it is the "news" section, I'd suggest under the title.

For example, "Sunday, March 29, 2020"  (so, definitely with written out month to avoid the useless order confusion with dd-mm and mm-dd)

**Comment by neteler** [comment]
Great, looks fine now.
