### ISSUE TITLE
Tryonline page should actually enable a user to get GRASS up and running in Rollapp 

### ISSUE THREAD

**Issue by AlisterH** [OSGeo/grass-website#417]
This page on the website links to Rollapp as an option to try the normal GRASS gui online: https://github.com/OSGeo/grass-website/content/learn/tryonline.md
Most prospective users would not have an existing Rollapp account, and would be unlikely to sign up for a paid account just to try GRASS for the first time.
When starting GRASS from a free "starter" Rollapp account a new user is likely to try to create a grass location in /home, and get stuck because it is read-only.  I suggest the user should be helped over this first hurdle.
Either:
- the tryonline page should tell users they can create the GRASS GIS database in the (hidden) /home/.grass7 directory, which is writable.
- or Rollapp should be contacted and asked to set a default GRASS GIS database directory, which is writable.

**Comment by wenzeslaus** [comment]
Thanks for bringing up this point. The current version (8.3) is much more suited for running in rollApp than the old version they have there (7.8). It even has some features which specifically address some of the issues you have encountered. I talked to them in the past, so I'll contact them to have the version updated and to smooth out any remaining rough edges.

**Comment by AlisterH** [comment]
Last week I was just running a script in it.  
Trying to test something else in it now (just to check behaviour on Linux) I find that it also doesn't seem to show any of the module dialogs.  The free account limits you to running one program at a time, so I guess rollApp thinks these are separate programs.  
If this is the same with later versions of GRASS there would really need to be some kind of fix for it to be a suitable environment for beginners to try GRASS.

**Comment by wenzeslaus** [comment]
For the record, I contacted their support on March 15.

I will leave this issue open on our side and wait for the response and resolution with rollApp. Then we can proceed here accordingly.

> The free account limits you to running one program at a time, so I guess rollApp thinks these are separate programs.

That was not the case in the past I think. I'll try to clarify that with them once then get back to me on the update. (One rollApp application was not one system process.)
