### ISSUE TITLE
Content header cutoff on mobile

### ISSUE THREAD

**Issue by cwhite911** [OSGeo/grass-website#424]
Content headers are getting cut off on mobile devices. I've not looked to see which layouts are impacted yet.

![image](https://github.com/OSGeo/grass-website/assets/3803800/0ca42c00-f2c3-4d62-95d5-ab399396b6b7)

**Comment by echoix** [comment]
It's funny, I made a screenshot on Friday for something similar, on Safari with an iPhone on iOS 17.4. 

![image](https://github.com/OSGeo/grass-website/assets/27212526/8fae9beb-539e-4414-afda-48abe220d840)

Its possible to scroll up to see the full title, until you lift your finger and goes back to this position.

**Comment by cwhite911** [comment]
Fixed the root cause of this in PR https://github.com/OSGeo/grass-website/pull/425
