### ISSUE TITLE
Historic "GRASS video" is not very visible

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#433]
At time the historic "GRASS video" is not very visible:

https://grass.osgeo.org/about/history/

![image](https://github.com/OSGeo/grass-website/assets/1295172/13ed6c41-4ce9-4fb8-9cfa-5f091e167c72)

- it is not clear that the screenshot points to a video
- no citation
- DOI not used

Related code:
https://github.com/OSGeo/grass-website/blob/aa9dfe8b9780d142eea07c660db8d68b943b411e/content/about/history.md?plain=1#L28

Suggestion:

- add a caption along with DOI (https://doi.org/10.5446/12963)
- make it somehow clear that this is the official video, not the "borrowed" copy on Youtube (which unfortunately has way more visibility) which was published by an person unknown to the GRASS GIS project

**Comment by veroandreo** [comment]
closing as complete
