### ISSUE TITLE
[Bug] grass.osgeo.org website down, can't download test data

### ISSUE THREAD

**Issue by echoix** [OSGeo/grass-website#441]
## Describe the bug

https://grass.osgeo.org/ seems to be down (502 bad gateway), so CI cannot download test data neither.

## To reproduce

Open https://grass.osgeo.org/ or https://grass.osgeo.org/sampledata/north_carolina/nc_spm_full_v2alpha2.tar.gz

## Expected behavior

https://grass.osgeo.org/sampledata/north_carolina/nc_spm_full_v2alpha2.tar.gz is downloadable for tests

## Screenshots

![image](https://github.com/OSGeo/grass/assets/27212526/fba849d6-a71f-4928-aca3-9e2546788042)

**Comment by neteler** [comment]
Thanks for the notification. Something killed apache, I have restarted it.

Site is back.

**Comment by echoix** [comment]
Looks up again, was a bit slow to display homepage, but at least it's back up!

**Comment by echoix** [comment]
@neteler There's also grasswiki that stayed down here
https://grasswiki.osgeo.org/

**Comment by neteler** [comment]
Also brought back: up & running again.

Weird coincidence...
