### ISSUE TITLE
Warnings when building with new hugo versions

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#45]
When locally building the website with the latest hugo version, I get:

```
WARN 2020/03/29 18:49:07 Page.Hugo is deprecated and will be removed in a future release. Use the global hugo function.
WARN 2020/03/29 18:49:07 Page.UniqueID is deprecated and will be removed in a future release. Use .File.UniqueID
WARN 2020/03/29 18:49:07 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
WARN 2020/03/29 18:49:07 .File.UniqueID on zero object. Wrap it in if or with: {{ with .File }}{{ .UniqueID }}{{ end }}
WARN 2020/03/29 18:49:07 .File.BaseFileName on zero object. Wrap it in if or with: {{ with .File }}{{ .BaseFileName }}{{ end }}
```

It might be relevant when the hugo version in the server gets updated, I guess.

**Comment by neteler** [comment]
Just a note on the new GRASS GIS server (Debian buster):

Currently we have:

`Hugo Static Site Generator v0.54.0/extended linux/amd64 BuildDate: 2019-06-04T19:16:36Z`

In the next Debian release it withh be hugo 0.68, but no idea when it will be released...

**Comment by nbozon** [comment]
Hugo is now at v0.69.0 ( see changelog here https://github.com/gohugoio/hugo/releases)

     Hugo Static Site Generator v0.69.0/extended darwin/amd64

**Comment by nbozon** [comment]
No more warnings when building the site with Hugo v.0.69.0 ! (see details [here](https://github.com/OSGeo/grass-website/commit/f372535464debafca0255c7b7d5e9c7efad50799) )
Let me then suggest we should upgrade soon -

**Comment by nbozon** [comment]
@veroandreo can you please try building again locally and confirm this also removes the warnings for you ? thx

**Comment by lucadelu** [comment]
For me yes! thanks @nbozon

**Comment by veroandreo** [comment]
No more warnings when building with new hugo version :)

**Comment by veroandreo** [comment]
Closing.
