### ISSUE TITLE
Display only an X number of news in News page

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#46]
We would need to display only an X number of news by default in the [News page](https://staging.grass.osgeo.org/news/) and keep then links to the list of per year news somewhere (upper or lower part of the page), so people can access them.

**Comment by neteler** [comment]
(related to issue #47)

**Comment by veroandreo** [comment]
This issue is not yet complete. We are missing the links to news lists per year. Shall I open a new one for that part?

**Comment by lucadelu** [comment]
Keep it open, but I have no clear idea how to implement the division per year... 
What do you suggest? Keep something like 10/15 in the news page and after have a list of year in the right side and people clicking on the year get all the news for that  year?

**Comment by veroandreo** [comment]
Suggestion was to keep only 3 as you did already for the News section in the Home page or even better display only the most recent one with its content and screenshot if available. For the rest, create links for 2020, 2019 and so on that will point to the full list of news of that year. These links could go either in the upper or lower part of the page as in https://staging.grass.osgeo.org/download/linux/ or as a side panel like in https://staging.grass.osgeo.org/contribute/development/

**Comment by lucadelu** [comment]
> Suggestion was to keep only 3 as you did already for the News section in the Home page or even better display only the most recent one with its content and screenshot if available. For the rest, create links for 2020, 2019 and so on that will point to the full list of news of that year. These links could go either in the upper or lower part of the page as in https://staging.grass.osgeo.org/download/linux/ or as a side panel like in https://staging.grass.osgeo.org/contribute/development/

I don't think is useful to have just one news if in the home pages we have already three. In addition if we want to put also the next events under the twitter stuff none will see the next events section if we don't provide any content to scroll down.

For the link,  I like the idea of another side panel, if we want to show few news, @nbozon what do you think?

**Comment by veroandreo** [comment]
> > Suggestion was to keep only 3 as you did already for the News section in the Home page or even better display only the most recent one with its content and screenshot if available. For the rest, create links for 2020, 2019 and so on that will point to the full list of news of that year. These links could go either in the upper or lower part of the page as in https://staging.grass.osgeo.org/download/linux/ or as a side panel like in https://staging.grass.osgeo.org/contribute/development/
> 
> I don't think is useful to have just one news if in the home pages we have already three. In addition if we want to put also the next events under the twitter stuff none will see the next events section if we don't provide any content to scroll down.

You are right. 

What I meant when I said display only one news was not only the link but the body news itself with its respective screenshot. That would then cover more space. But, yes, if the news is short or does not have a screenshot, then we won't have content to scroll down. So, leave it as is.

> For the link, I like the idea of another side panel, if we want to show few news, @nbozon what do you think?

+1

**Comment by nbozon** [comment]
The display of the news list has been improved in [master](https://staging.grass.osgeo.org/news/), as follows:
- Sorts news item by year
- Creates a bootstrap accordion, with one collapsible panel per year
- Collapses the first panel by default (only news from the current year are shown) 
- Previous years are not shown by default and can be collapsed by click
- Adds a calendar icon on every published date (".entry-meta")
- Adds various CSS improvements
<img width="423" alt="Capture d’écran 2020-05-30 à 10 47 31" src="https://user-images.githubusercontent.com/7135374/83324097-1a01a980-a263-11ea-8334-2d9b8dcc15d0.png">
Is it better like this @veroandreo @lucadelu @neteler  ?

**Comment by neteler** [comment]
I like it a lot! Great

**Comment by veroandreo** [comment]
looks great! :)

**Comment by neteler** [comment]
May we close this?

**Comment by veroandreo** [comment]
I believe so. Closing
