### ISSUE TITLE
[Bug] Development Quick links point to trac and not to GitHub

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#472]
Not sure if on purpose but the

**Quick links**
- [Submitting guidelines](https://trac.osgeo.org/grass/wiki/Submitting) - old trac
- [How to use git](https://trac.osgeo.org/grass/wiki/HowToGit) - old trac

should probably link to
- https://github.com/OSGeo/grass/blob/main/doc/development/style_guide.md
- https://github.com/OSGeo/grass/blob/main/doc/development/github_guide.md

The lines to be changed would be:

https://github.com/OSGeo/grass-website/blob/38a9fc4c5aa3d4f7abbd91460857a3b73c6a44dd/themes/grass/layouts/contribute/devel.html#L37
https://github.com/OSGeo/grass-website/blob/38a9fc4c5aa3d4f7abbd91460857a3b73c6a44dd/themes/grass/layouts/contribute/devel.html#L38

**Comment by wenzeslaus** [comment]
Yes, that is correct. Just old doc. I was thinking if to even have these links there, but Quick Links under [Contribute > Development](https://grass.osgeo.org/contribute/development/) looks appropriate. Is that what you are looking at?

**Comment by neteler** [comment]
I am confused. Why do we point to (outdated?) trac and not to the new documents in GitHub?

**Comment by wenzeslaus** [comment]
I mean your analysis is correct. It's just old doc, no idea behind it.
