### ISSUE TITLE
Links broken in L.A.S. and GRASSLAND link in GRASS in Transition

### ISSUE THREAD

**Issue by wenzeslaus** [OSGeo/grass-website#479]
This is low priority, but some historical links are broken in [GRASS in Transition](https://grass.osgeo.org/news/cerl1996/) (from CERL) page.

Source: [content/news/cerl1996/transition.html](https://github.com/OSGeo/grass-website/blob/f5067609be502312e2873324fdc0d05b105fa02a/content/news/cerl1996/transition.html)

Links:

```
http://www.las.com/grassland ([L.A.S. and GRASSLAND Information](http://www.las.com/grassland))
http://www.cecer.army.mil/ (back to CERL homepage)
https://grass.osgeo.org/news/cerl1996/GRASS.main.html (logo with text OPEN GIS)
https://grass.osgeo.org/news/cerl1996/viz/viz_group.html (Bill Brown)
```

All four plus Bill Brown's email were meant specifically for the transition time (the page says "Last Modified: March 31 1996"). We can probably simply edit the page to remove the links and add a note about that.

**Comment by neteler** [comment]
I'd suggest to point to their respective web archive entries.

**Comment by itsadityaaaaa** [comment]
I Want to work on this issue, can you please assign it to me.

**Comment by neteler** [comment]
> I Want to work on this issue, can you please assign it to me.

You are welcome to work on it!

For some introduction to `grass_web`, see [README.md](https://github.com/OSGeo/grass-website/blob/master/README.md).

**Comment by veroandreo** [comment]
closing as completed
