### ISSUE TITLE
Mobile version: reduce margins and font size

### ISSUE THREAD

**Issue by mlennert** [OSGeo/grass-website#48]
Currently, on mobile devices, margins are very large and thus force the reader to scroll a lot when there is a certain amount of text.
Also, font size is probably a bit too big.

**Comment by nbozon** [comment]
Thanks @mlennert for this feedback.  Margins, paddings and font size are now set smaller on mobile screens through extended css media queries. Deployed in master, visible on staging. See example comparison bellow

Home 

| before | after  | 
|------|-----|
| <img width="211" alt="Capture d’écran 2020-05-24 à 07 58 49" src="https://user-images.githubusercontent.com/7135374/82747177-f2a86980-9d96-11ea-9724-5a0a0ba7fba6.png">| <img width="211" alt="Capture d’écran 2020-05-24 à 08 15 59" src="https://user-images.githubusercontent.com/7135374/82747164-d3a9d780-9d96-11ea-928c-98101ce6da87.png">

Download

| before | after  | 
|------|-----|
| <img width="211" alt="Capture d’écran 2020-05-24 à 07 58 49" src="https://user-images.githubusercontent.com/7135374/82747485-72cfce80-9d99-11ea-87ee-9f7f50847b13.png">| <img width="211" alt="Capture d’écran 2020-05-24 à 08 15 59" src="https://user-images.githubusercontent.com/7135374/82747493-9561e780-9d99-11ea-8553-3d0f916ad2bc.png">

Overview

| before | after  | 
|------|-----|
| <img width="211" alt="Capture d’écran 2020-05-24 à 07 58 49" src="https://user-images.githubusercontent.com/7135374/82747511-d4903880-9d99-11ea-9c10-d8f5aa36727f.png">| <img width="211" alt="Capture d’écran 2020-05-24 à 08 15 59" src="https://user-images.githubusercontent.com/7135374/82747517-e671db80-9d99-11ea-850e-de8880048ee9.png">

**Comment by mlennert** [comment]
Thanks a lot ! Looks good now.
