### ISSUE TITLE
Migrate gallery content from CMS (original screenshots)

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#50]
Migrate gallery content (original PNG files from the CMS) into

* /static/images/gallery/

**Comment by neteler** [comment]
I have locally cleaned up the files (thumbnails removed, de-duplicated).
There are now 199 files in this structure:

```
3D/
books/
cartography/
community/
conferences/
grass_screenshots/
gui/
lidar/
raster/
remote_sensing/
vector/
```

Question: upload or not?

**Comment by veroandreo** [comment]
I would upload. How heavy is it, altogether?

**Comment by neteler** [comment]
I guess it's ok for a gallery...

`74M	gallery/`

**Comment by mlennert** [comment]
> I guess it's ok for a gallery...
> 
> `74M gallery/`
> 
> Objections to upload?

No, go ahead.
