### ISSUE TITLE
Add logo files and logos' links

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#52]
We need a folder with all the logos in different formats and then add  the respective links here: https://staging.grass.osgeo.org/about/brand/

**Comment by ecodiv** [comment]
Perhaps show the most important ones, and have a download link that allows downloading all other (old, special) logos.

**Comment by neteler** [comment]
TODO: update brand page with respective links

**Comment by lucadelu** [comment]
started with #74, I added:
* SVG and EPS file link
* black&white and color PNG files 

should we add also other versions (like with slogan) other formats?

**Comment by veroandreo** [comment]
> started with #74, I added:
> 
>     * SVG and EPS file link
> 
>     * black&white and color PNG files
> 
> 
> should we add also other versions (like with slogan) other formats?

No, I'd keep it short. Maybe add a link to banner and splash screen if you want (?).

**Comment by lucadelu** [comment]
Maybe a link to logos directory could be useful or a dedicated page with gallery (#25)

**Comment by veroandreo** [comment]
a gallery would be nice

**Comment by veroandreo** [comment]
closing as completed
