### ISSUE TITLE
Add a "Next events" section

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#54]
It would be nice to have a small section where to put logos (one or two) of next events either in the landing page or in [News](https://staging.grass.osgeo.org/news/). In the latter, the space for the tweets could be shrunk a bit, and add next events logo(s) with link(s) there.

**Comment by lucadelu** [comment]
Started in #64

**Comment by lucadelu** [comment]
"Next events" section is now in News page, in the pull request there was discussion about the position of the section. I have the same idea of @mlennert that it is more useful to have first the Twitter and than "Next events", however is simple to change if majority prefer other solution.
