### ISSUE TITLE
Add graphical timeline to history

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#56]
We would like to have a graphical representation of releases and important dates in the History (sub)page. Might be something similar to https://grass.osgeo.org/uploads/images/grass_5_6_roadmap_graphic.jpg for the releases

**Comment by hellik** [comment]
> 
> 
> We would like to have a graphical representation of releases and important dates in the History (sub)page. Might be something similar to https://grass.osgeo.org/uploads/images/grass_5_6_roadmap_graphic.jpg for the releases

yes, such a graphical timeline would be nice

**Comment by nbozon** [comment]
A simple responsive timeline was added and the whole History subsection was improve, slightly revamped on master, please review the following pages @veroandreo @neteler @lucadelu @mlennert 
- General history page:
https://staging.grass.osgeo.org/about/history/
- GRASS GIS release timeline page:
https://staging.grass.osgeo.org/about/history/releases/
- GRASS website evolution page:
https://staging.grass.osgeo.org/about/history/web-evolution/
- Van Warren's note page:
https://staging.grass.osgeo.org/about/history/van-warren-notes/
- First GNU release page:
https://staging.grass.osgeo.org/about/history/gnu-release/

**Comment by lucadelu** [comment]
@nbozon I really like your improvements, thanks. Probably the Vero request was for something different but I think the image is not needed for the first release, we can work on that later

**Comment by neteler** [comment]
Great work, @nbozon !

**Comment by veroandreo** [comment]
it looks great @nbozon !

**Comment by mlennert** [comment]
Looks good to me, too.

**Comment by neteler** [comment]
Seems to be done, closing with thanks to @nbozon !
