### ISSUE TITLE
Add a "website contributor's manual"

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#57]
It would be nice to have instructions and examples on how to contribute to the website, which template/layout to use for different types of pages, styles, and so on. This could probably be part of the README in the website repo or become a section in contribute/development. It could also go in https://staging.grass.osgeo.org/about/elements/. Not sure which is the best option.

**Comment by lucadelu** [comment]
I think README could be the better place, @nbozon it seems possible to read a file in hugo (https://gohugo.io/functions/readfile/)

**Comment by neteler** [comment]
A draft appears to be here:

https://github.com/OSGeo/grass-website/blob/master/README.md

**Comment by veroandreo** [comment]
plus this: https://grass.osgeo.org/about/theme/

For someone trying to contribute a blog/news post should be enough. I close this one as done then. Thanks @nbozon :)
