### ISSUE TITLE
Add "Try GRASS GIS online" button

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-website#59]
@wenzeslaus produced some cool stuff that allows to try GRASS GIS online, with plenty of nice examples:

Would be cool to have it referenced from the new website.

See: 
http://osgeo-org.1560.x6.nabble.com/Try-GRASS-GIS-online-Binder-mybinder-org-td5412744.html
 or 
http://osgeo-org.1560.x6.nabble.com/Try-GRASS-GIS-online-rollApp-rollapp-com-td5425767.html

**Comment by veroandreo** [comment]
+1! It could go in [Learn](/content/learn) landing page (i.e., in one of those squares) and maybe also in the main page (i.e., home) either as a button or as a rectangle such as those in the Download landing page. What do you think, @nbozon ?

**Comment by wenzeslaus** [comment]
See also how Jupyter project does it:

[Index page](https://jupyter.org/) has "Try it in your browser" button next to "Install JupyterLab" (under JupyterLab section).

The [Try Jupyter](https://jupyter.org/try) page has series of examples for different technologies (Classic Notebook, JupyterLab) or interest groups (R, C++)* as boxes with title, image and description. The URL for the page is `https://jupyter.org/try`.

*Related to that, I think we should have there more than one option too. There is even more than mybinder and rollApp.

**Comment by ninsbl** [comment]
Now I had a look at CoCalc tryout:
https://cocalc.com/app?anonymous=x11
Unfortunately, for me responsetime was quite slow. So I am in doubt if this is good "advertisement".
How does it work for others. Another limitation is that sample data is missing and the free CoCalc instance cannot download…
Any thought? Add CoCalc or leave it?

**Comment by neteler** [comment]
I'd include CoCalc for now, we may add a (grey font) note that the service might be slow.

**Comment by veroandreo** [comment]
I'm not sure about it... They have GRASS 7.4 (old-ish), it is really slow and you have to download a location which at least here did not work... I would not include it for now

**Comment by ninsbl** [comment]
OK, I am currently implementing Luca`s suggestion with a sub-page under learn. Where I for starters add different option (also the less optimal ones).
But now I am wondering, is there anywhere an actinia test instance available that could be added as "Try GRASS GIS as a Service"? And if there is one would that be of interest in this context?

**Comment by ninsbl** [comment]
See also updates in #80

**Comment by veroandreo** [comment]
> See also updates in #80

Given all the limitations of CoCalc, I really would not include it... It is a bad experience IMO and I think we must assume that most newcommers won't have a paid account as to enjoy trying GRASS in CoCalc

**Comment by ninsbl** [comment]
No problem. Main point was to show how we may present such options. Now I commented out CoCalc (maybe rollApp is not that much better (or even worse).
In the X11 interface you have no web access, so location download does not work. However, in the files section sample data can be uploaded...

**Comment by neteler** [comment]
@ninsbl do you have any contact with CoCalc - to ask them if they could upgrade their installation? The current instance isn't really usable as already pointed out...

**Comment by ninsbl** [comment]
> @ninsbl do you have any contact with CoCalc - to ask them if they could upgrade their installation? The current instance isn't really usable as already pointed out...

CoCalc has a price plan where one could pay for more (dedicated) compute resources. So I doubt they would increase available resources in the free plan. However, from my point of view, the lack of sample data is the bigger issue anyway. And that might be solvable...? E.g. with a grass-data package?

**Comment by ninsbl** [comment]
fixed in #80
For the sample data problem in CoCalc we could open a separate ticket!?

**Comment by veroandreo** [comment]
> For the sample data problem in CoCalc we could open a separate ticket!?

yes :)
