### ISSUE TITLE
brand icons broken

### ISSUE THREAD

**Issue by landam** [OSGeo/grass-website#63]
Brand icons seems to be broken, see https://staging.grass.osgeo.org/about/brand/

![broken-icons](https://user-images.githubusercontent.com/5683186/77950819-63686380-72c9-11ea-8240-7a72328737d2.png)

**Comment by lucadelu** [comment]
I fixed them #74, I added:
* SVG and EPS file link
* black&white and color PNG files 

should we add also other versions (like with slogan) other formats?

**Comment by lucadelu** [comment]
fixed #74
