### ISSUE TITLE
Content from GRASS flyers into Overview?

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#66]
What about adding some of the content from the [OSGeo-GRASS flyer](https://github.com/OSGeo/osgeo/blob/master/marketing/print/one-page-info/eu/grass_gis_a4.pdf) and our own [flyer by Vincent](https://trac.osgeo.org/grass/browser/grass-promo/grassflyer/flyer_2016/en/grass_flyer.pdf?rev=70414) into the [General Overview](https://staging.grass.osgeo.org/learn/overview/)?? Especially the "Main features" and "Interoperability" or "Interfaces" parts.

With these plus an Add-ons section, I think this page can be a good overview of GRASS :-)

Opinions @lucadelu @neteler @mlennert ?

**Comment by mlennert** [comment]
> What about adding some of the content from the [OSGeo-GRASS flyer](https://github.com/OSGeo/osgeo/blob/master/marketing/print/one-page-info/eu/grass_gis_a4.pdf) and our own [flyer by Vincent](https://trac.osgeo.org/grass/browser/grass-promo/grassflyer/flyer_2016/en/grass_flyer.pdf?rev=70414) into the [General Overview](https://staging.grass.osgeo.org/learn/overview/)?? Especially the "Main features" and "Interoperability" or "Interfaces" parts.
> 
> With these plus an Add-ons section, I think this page can be a good overview of GRASS :-)

The general idea was to keep pages as short and sweet as possible, so I would rather not enrich this first page too much. I would rather create some links (using sexy buttons ?) pointing to some exciting details about GRASS.
Maybe another option could be to directly link to the flyer ? Also to try to have only one place where each information needs to be updated ? Thus, the flyer would be the place for the more detailed overview...

Or find a way to link the two, e.g. have a detailed overview page (linked to from the general overview) and find a way to automagically translate this into a flyer when needed...

**Comment by nbozon** [comment]
IMO, part of the flyer content may be reused in the General Overview, but the latter should not contain more than four sections (What is GRASS, Genral presentation, Main features and Community for example). These should indeed contain many links to other pages as suggested -

The flyer itself (with link to ressource on github) may also be added in the Brand page ...

**Comment by veroandreo** [comment]
> IMO, part of the flyer content may be reused in the General Overview, but the latter should not contain more than four sections (What is GRASS, Genral presentation, Main features and Community for example). These should indeed contain many links to other pages as suggested -
> 
> The flyer itself (with link to ressource on github) may also be added in the Brand page ...

Agreed :) 
Will work on this during the weekend
