### ISSUE TITLE
Add "edit on GitHub" link or button

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#7]
I saw that https://gdal.org/ has a nice link "Edit on GitHub" to create PR suggesting changes to documentation. Can we have that for the website too so anyone wanting to contribute or spotting some error can easily create a PR?

**Comment by nbozon** [comment]
+1, great idea. 
I will try to add that, may be directly as a link item in the 'Contribute' submenu ? (as for Wiki), or somewhere visible enough on the front page...(And there's already the link to Github repo in the footer too).

**Comment by neteler** [comment]
> +1, great idea.
> I will try to add that, may be directly as a link item in the 'Contribute' submenu ? (as for Wiki), or somewhere visible enough on the front page...

On the GDAL and Proj pages it is individual for each page, not one central link...

**Comment by rouault** [comment]
> On the GDAL and Proj pages it is individual for each page, not one central link...

It's a feature on the Sphinx "Read the docs" theme we are using. Settings here : https://github.com/OSGeo/gdal/blob/master/gdal/doc/source/conf.py#L53

**Comment by nbozon** [comment]
A link was added in the footer of every 'sub pages' , as shown bellow:
<img width="1133" alt="page-github-link" src="https://user-images.githubusercontent.com/7135374/71578253-a7e03980-2af7-11ea-8e4a-ceb9b91a0b0f.png">

We would likely prevent contributors to edit the home page or section pages, by not showing this link on the latter. The link only shows up on the website 'sub pages' for now ( [here](http://staging.grass.osgeo.org/about/community/) for example), as follows:

	{{ if not .Data.Pages }}
	<p><small><a href="https://github.com/OSGeo/grass-website/tree/master/content/{{ .Section }}/{{ .File.BaseFileName }}.md" class="fa fa-github"> <span class="edt">Edit this page on GitHub</span></a></small></p>
	{{ end }}

Would it work this way ?

**Comment by neteler** [comment]
(for reference, this was added in 64ea0f051f97b2870ef7c089c3b5a9472a97916b)
