### ISSUE TITLE
Improve content of First Time User page

### ISSUE THREAD

**Issue by mlennert** [OSGeo/grass-website#70]
Ideas:

- pictures (but we have to see about rights): see #67 for some suggestions of images

- add a glossary page with some important GRASS GIS specific concepts (database structure, computational region, vector layers, etc...)

**Comment by wenzeslaus** [comment]
Possible starting point (at least for the list and some definitions):

https://grasswiki.osgeo.org/wiki/Terminology_comparison_between_ArcGIS_and_GRASS_GIS

**Comment by veroandreo** [comment]
I added some other links and screenshots in #125

**Comment by lucadelu** [comment]
I suggest to move the videocamera icon up to the text just down the title

**Comment by veroandreo** [comment]
> I suggest to move the videocamera icon up to the text just down the title

I agree, done and merged in #136 :)

**Comment by lucadelu** [comment]
Thanks, are you able to add some more words to have one more line in the first sentence?

(for a graphical point of view should be better to have the list at the same space in the left border, we can fix it also by css, however the text solution is good and it work already in table e mobile view, only desktop has the problem)

**Comment by neteler** [comment]
To me the page now looks quite nice:
https://staging.grass.osgeo.org/learn/newcomers/

**Comment by veroandreo** [comment]
> Thanks, are you able to add some more words to have one more line in the first sentence?
> 
> (for a graphical point of view should be better to have the list at the same space in the left border, we can fix it also by css, however the text solution is good and it work already in table e mobile view, only desktop has the problem)

addressed in #145, please check

**Comment by mlennert** [comment]
>     * add a glossary page with some important GRASS GIS specific concepts (database structure, computational region, vector layers, etc...)
After some reflection, I think this would probably be better off on the wiki than on the website. What do you think ?

**Comment by veroandreo** [comment]
> > ```
> > * add a glossary page with some important GRASS GIS specific concepts (database structure, computational region, vector layers, etc...)
> > ```
> 
> After some reflection, I think this would probably be better off on the wiki than on the website. What do you think ?

Since in the `First time user` page we are providing links to the manual pages and some intro tutorials and courses where all these concepts are explained in full, I do not think we need to add a glossary in the website

**Comment by veroandreo** [comment]
Closing, feel free to re-open if fixes are not satisfactory or just make new PRs with enhancements :)
For a first release, I believe this page is fine now
