### ISSUE TITLE
Sample data: illustrate download from GRASS with a screenshot

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-website#71]
Implement Moritzs suggestion to iIllustrate downoad from GRASS GIS with a screenshot like [this one.](https://trac.osgeo.org/grass/attachment/wiki/Grass7/NewFeatures74/grass740_startup_sample_data_download_arrow.png)

Maybe wait until gallery content is uploaded?

**Comment by mlennert** [comment]
There was not relevant image in the gallery. I just added it:  #75 .
