### ISSUE TITLE
Create/Edit content of Contribute landing page

### ISSUE THREAD

**Issue by mlennert** [OSGeo/grass-website#77]
The contribute landing page is still missing content.

**Comment by ninsbl** [comment]
Same is true for Learn

**Comment by mlennert** [comment]
See #60.

**Comment by neteler** [comment]
Maybe use material from https://grass.osgeo.org/get-involved/ ?

**Comment by veroandreo** [comment]
We already have a very nice "Get involved" section in contribute/development, with icons and all... Shall we move that into Contribute landing page?? Then, into Development page we can put some of the content from the link suggested by @neteler (ideally) without repeating too much; maybe keep the development section pretty technical

**Comment by lucadelu** [comment]
I agree with @veroandreo proposal, I would move "get involved" in contribute and remove that page, what do you think?

**Comment by nbozon** [comment]
+1

**Comment by veroandreo** [comment]
See #118
