### ISSUE TITLE
Landing pages can only be reached from buttons on home

### ISSUE THREAD

**Issue by ninsbl** [OSGeo/grass-website#78]
Landing pages can only be reached from buttons on home, and not from e.g. menu at the top.

This way, one has to go forth and back to be able to discover all of them.

Is that on purpose? Or is it a browser issue?

**Comment by mlennert** [comment]
AFAIU, this is on purpose since the landing pages are not ready, yet.

**Comment by veroandreo** [comment]
I noticed the same... I'd like to see the landing pages (even if not ready yet) also when clicking the menu at the top.

**Comment by hellik** [comment]
> 
> 
> I noticed the same... I'd like to see the landing pages (even if not ready yet) also when clicking the menu at the top.

+1

**Comment by lucadelu** [comment]
Answer is [here](https://github.com/OSGeo/grass-website/issues/93#issuecomment-613249047), closing. 
Reopen if not clear.

**Comment by veroandreo** [comment]
I don't think the problem or issue addressed here has been fixed or answered. AFAIU, the question was why can't we access the landing pages from the menus in the top part instead we have to go back to home everytime?

**Comment by nbozon** [comment]
One does not necessarily need to go back home each time, but can click the link to the section index  from the breadcrumb, available on every page.

**Comment by nbozon** [comment]
**Important note:** This is not the standard behavior of bootstrap powered navigation menus.
This means adding click (go to url) + hover event (toggle dropdown) on primary links , which is not supported on mobile (no hover event on mobile, that is why this is not implemented in the boostrap core btw).

**Comment by nbozon** [comment]
fixed on staging  -  Primary menu items are now clickable on screens wider than 768 px. Their behavior stays unchanged on mobile  though (tap to toggle dropdown), as this is not possible to fire two events from the same link. Mobile users will use the link available from the breadcrumb :)

**Comment by veroandreo** [comment]
Thanks :)
