### ISSUE TITLE
https://staging.grass.osgeo.org/download/ - regular URL?

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass-website#86]
just found by chance following URL in google:

https://staging.grass.osgeo.org/download/

it looks like

![download](https://user-images.githubusercontent.com/12000843/78586193-63251680-783b-11ea-82e9-1c3df46bf3eb.PNG)

only with the grass logo, but without any background on the top.

this site can't be accessed from https://staging.grass.osgeo.org/

is this a correct URL? should this be hidden?

**Comment by hellik** [comment]
ok I found it now, it's linked from the landing page by clicking on _download_:

![download2](https://user-images.githubusercontent.com/12000843/78588858-9e294900-783f-11ea-9f84-d4f912ff4a5c.PNG)

**Comment by neteler** [comment]
@hellik it seems to be fixed. Please check again

**Comment by veroandreo** [comment]
The issue was fixed. Closing.
