### ISSUE TITLE
shouldn't top of subpages have a smaller header?

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass-website#87]
these are:

https://staging.grass.osgeo.org/download/
https://staging.grass.osgeo.org/learn/

![download](https://user-images.githubusercontent.com/12000843/78589234-2dcef780-7840-11ea-9f61-97141d8a633d.PNG)

![learn](https://user-images.githubusercontent.com/12000843/78589244-31fb1500-7840-11ea-8602-788ef79066d8.PNG)

at least here on my laptop with a medium screen and on my tablet, this produces a unecessary scrolling down.

will there be some background picture (behind the logo) added?

**Comment by nbozon** [comment]
Agreed. This is now fixed, please see:
https://staging.grass.osgeo.org/download/
https://staging.grass.osgeo.org/learn/
https://staging.grass.osgeo.org/contribute/

**Comment by hellik** [comment]
Yes, it's better now. Closing issue.
