### ISSUE TITLE
download GRASS GIS source code on several places - should it be only on 1 place?

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass-website#88]
it's in https://staging.grass.osgeo.org/download/

![sourcecode1](https://user-images.githubusercontent.com/12000843/78594065-ec424a80-7847-11ea-8e68-6e495e18c152.PNG)

and in https://staging.grass.osgeo.org/download/linux/

![sourcecode2](https://user-images.githubusercontent.com/12000843/78594109-ffedb100-7847-11ea-8131-b5b9478765fd.PNG)

it should be removed from the linux download page.

**Comment by lucadelu** [comment]
I agree

**Comment by nbozon** [comment]
This has been removed from the Download Linux page - closing
