### ISSUE TITLE
information about license should be in 1 place - avoid duplication

### ISSUE THREAD

**Issue by hellik** [OSGeo/grass-website#90]
at time, in https://staging.grass.osgeo.org/learn/overview/

there is a paragraph/sentence about license, see

![license](https://user-images.githubusercontent.com/12000843/78707397-d8aee680-7910-11ea-9cf2-ada36196a619.PNG)

according to #32

_License page improvements in aa19522 and added to menu in 3f9937c_

there should be an entry in the about menue, but there isn't at the moment. maybe not merged yet.

when there is a legal subpage available, this sentence should be removed.

**Comment by mlennert** [comment]
> at time, in https://staging.grass.osgeo.org/learn/overview/
> 
> there is a paragraph/sentence about license, see
> 
> ![license](https://user-images.githubusercontent.com/12000843/78707397-d8aee680-7910-11ea-9cf2-ada36196a619.PNG)
> 
> according to #32
> 
> _License page improvements in aa19522 and added to menu in 3f9937c_
> 
> there should be an entry in the about menue, but there isn't at the moment. maybe not merged yet.
> 
> when there is a legal subpage available, this sentence should be removed.
> 

A page exists, just not referenced, yet, from anywhere:

https://staging.grass.osgeo.org/about/license/

It is a bit too cluttered in my view, especially on a phone, so it probably needs some more love, and integration into the menu.

**Comment by lucadelu** [comment]
Since the license page is now referenced in the menu I'm going to close the issue, please reopen if needed
