### ISSUE TITLE
Mysterious "Abouts" page

### ISSUE THREAD

**Issue by neteler** [OSGeo/grass-website#93]
There is an "Abouts" page which looks a bit weird - apparently auto-generated:

https://staging.grass.osgeo.org/about/

![image](https://user-images.githubusercontent.com/1295172/78836206-ed16e000-79f1-11ea-8613-0c6f0e93c9b5.png)

Do we want this? It seems to come from

```
ag NNNH
themes/grass/layouts/_default/list.html
79:	      <h3 class="mt-0">NNNH</h3>
```

**Comment by nbozon** [comment]
We basically do not want people to reach this page, that's why it wasn't created yet, and autogenerated by Hugo. This is now fixed:
https://staging.grass.osgeo.org/about/
Please note that the breadcrumb links are deactivated for every About page, in order to prevent people visiting this index page.

**Comment by lucadelu** [comment]
> We basically do not want people to reach this page, that's why it wasn't created yet, and autogenerated by Hugo. This is now fixed:
> https://staging.grass.osgeo.org/about/

I will improve a little bit this

> Please note that the breadcrumb links are deactivated for every About page, in order to prevent people visiting this index page.

I agree, the breadcrumb links should be deactivated.

**Comment by neteler** [comment]
It now looks better to me (however, what appears and what not isn't fully clear to me)

**Comment by nbozon** [comment]
All subpages from the About section are listed there (i.e all md files in the /about directory) @neteler

**Comment by veroandreo** [comment]
IMO, it is not right that all subpages are listed there. For example, it does not make sense to me to have the Van Warren's historical notes or the website evolution or the release list there, because all those are "childs" of history (and they are indeed within about/history folder)... In this about index page only the submenus should appear, no?

**Comment by lucadelu** [comment]
Yes I agree, subdirectories pages should not appear..

**Comment by nbozon** [comment]
Fixed, only pages at the root of the /about directory are now listed. Pages from any subdirectories (like /about/history/ ) will be ignored

       {{ range where .Pages "File.Dir" "in" "/about/" }}

@veroandreo @lucadelu  please check and close this issue

**Comment by veroandreo** [comment]
I think it is correct now, thanks!
