### ISSUE TITLE
Contact information (correct?)

### ISSUE THREAD

**Issue by landam** [OSGeo/grass-website#94]
Is really contact information correct (address)?

https://staging.grass.osgeo.org/about/credits/

![Screenshot_2020-04-08 Credits](https://user-images.githubusercontent.com/5683186/78836946-63681200-79f3-11ea-8dd9-7753980c5636.png)

**Comment by neteler** [comment]
Technically maybe yes but nobody will answer. In other places the PSC chair address is specified (so, Bonn).

**Comment by neteler** [comment]
Here we have the Bonn address: https://grass.osgeo.org/grass78/source/COPYING
