### ISSUE TITLE
Enhance releases detailed list formatting and appearence

### ISSUE THREAD

**Issue by veroandreo** [OSGeo/grass-website#95]
- 7.8.1 and 7.8.2 are missing (if this will be a full list, maybe we should also add them here)
- RC's after 7.2.0 are missing while all other RC are there
- Most of version 6 and earlier releases are not in bold (we could agree here what to put in bold to make it consistent through out the list, I'd suggest only major releases)
- Split the list in sections, either decades as in History or some other criteria
- Was it called GRASS GIS before version 4?
- 1990 (Winter) GRASS 3.2 released through Internet <-- will links like this one be maintained?
- Beautify by adding numerous of the historic screenshots from the gallery: https://github.com/OSGeo/grass-website/tree/master/static/images/gallery/gui/ and https://github.com/OSGeo/grass-website/tree/master/static/images/gallery/3D/
- add some more historical contextual notes here and there

**Comment by neteler** [comment]
Current state after today's continued cleanup: https://staging.grass.osgeo.org/about/history/releases/

TODO:

- Beautify by adding numerous of the historic screenshots from the gallery: https://github.com/OSGeo/grass-website/tree/master/static/images/gallery/gui/ and https://github.com/OSGeo/grass-website/tree/master/static/images/gallery/3D/
